#!/usr/bin/env python
from __future__ import annotations


SUMMARY_VERIFY_CODES = {
    "REPORTS_MISSING": "E_SUMMARY_VERIFY_REPORTS_MISSING",
    "SUMMARY_PATH_MISSING": "E_SUMMARY_VERIFY_SUMMARY_PATH_MISSING",
    "SUMMARY_FILE_MISSING": "E_SUMMARY_VERIFY_SUMMARY_FILE_MISSING",
    "STATUS_MISSING": "E_SUMMARY_VERIFY_STATUS_MISSING",
    "STATUS_MISMATCH": "E_SUMMARY_VERIFY_STATUS_MISMATCH",
    "PASS_FAILED_STEPS_NOT_NONE": "E_SUMMARY_VERIFY_PASS_FAILED_STEPS_NOT_NONE",
    "PASS_HAS_DETAIL": "E_SUMMARY_VERIFY_PASS_HAS_DETAIL",
    "PASS_HAS_LOGS": "E_SUMMARY_VERIFY_PASS_HAS_LOGS",
    "FAIL_FAILED_STEPS_EMPTY": "E_SUMMARY_VERIFY_FAIL_FAILED_STEPS_EMPTY",
    "DETAIL_FORMAT_INVALID": "E_SUMMARY_VERIFY_DETAIL_FORMAT_INVALID",
    "DETAIL_RC_ZERO": "E_SUMMARY_VERIFY_DETAIL_RC_ZERO",
    "DETAIL_CMD_EMPTY": "E_SUMMARY_VERIFY_DETAIL_CMD_EMPTY",
    "DETAIL_NOT_IN_FAILED_STEPS": "E_SUMMARY_VERIFY_DETAIL_NOT_IN_FAILED_STEPS",
    "FAIL_DETAIL_MISSING": "E_SUMMARY_VERIFY_FAIL_DETAIL_MISSING",
    "LOGS_FORMAT_INVALID": "E_SUMMARY_VERIFY_LOGS_FORMAT_INVALID",
    "LOGS_NOT_IN_FAILED_STEPS": "E_SUMMARY_VERIFY_LOGS_NOT_IN_FAILED_STEPS",
    "LOG_PATH_MISSING": "E_SUMMARY_VERIFY_LOG_PATH_MISSING",
    "SUMMARY_FAILED_STEP_NOT_IN_INDEX": "E_SUMMARY_VERIFY_SUMMARY_FAILED_STEP_NOT_IN_INDEX",
    "DETAIL_NOT_IN_INDEX": "E_SUMMARY_VERIFY_DETAIL_NOT_IN_INDEX",
    "LOGS_NOT_IN_INDEX": "E_SUMMARY_VERIFY_LOGS_NOT_IN_INDEX",
}
