#[cfg(not(target_arch = "wasm32"))]
pub mod ai_prompt;
#[cfg(not(target_arch = "wasm32"))]
pub mod ai_extract_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod alrim_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod bogae_bundle_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod bogae_playback_workflow;
pub mod canon;
pub mod corpus_authoring;
pub mod corpus_csv;
#[cfg(not(target_arch = "wasm32"))]
pub mod cert_workflow;
pub mod currentline_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod dataset_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod repl_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod replay_diff;
pub mod ddn_runtime;
pub mod deterministic_debug;
#[cfg(not(target_arch = "wasm32"))]
pub mod dotbogi_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod bdl_packet;
#[cfg(not(target_arch = "wasm32"))]
pub mod observation_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod asset_manifest;
#[cfg(not(target_arch = "wasm32"))]
pub mod tensor_artifact;
#[cfg(not(target_arch = "wasm32"))]
pub mod goal_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod latency_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod safety_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod scan_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod intent_workflow;
pub mod input_tape;
pub mod host_resource;
#[cfg(not(target_arch = "wasm32"))]
pub mod live_input;
pub mod geoul_snapshot;
#[cfg(not(target_arch = "wasm32"))]
pub mod geoul_bundle;
#[cfg(not(target_arch = "wasm32"))]
pub mod geoul_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod goap_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod world_diff_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod workshop_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod heal_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod story_timeline_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod train_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod eval_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod edu_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod evolve_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod evolving_universe_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod gateway_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod imitation_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod infer_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod proof_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod reward_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod symbolic_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod swarm_workflow;
pub mod domain_evidence_manifest;
pub mod file_meta;
mod fixed64_boundary;
pub mod gate0_registry;
#[cfg(not(target_arch = "wasm32"))]
pub mod gaji_seal_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod gaji_plan_workflow;
pub mod local_project;
pub mod lint;
pub mod lsp;
pub mod model_runtime;
#[cfg(not(target_arch = "wasm32"))]
pub mod numeric_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod nurigym_workflow;
pub mod preprocess;
pub mod primary_view;
pub mod project_authoring;
#[cfg(not(target_arch = "wasm32"))]
pub mod patch_workflow;
pub mod runtime_surface;
pub mod sealed_domain_dataset;
#[cfg(not(target_arch = "wasm32"))]
pub mod seulgi_bundle_workflow;
#[cfg(test)]
mod self_contained_test_sources;
pub mod source_analysis;
#[cfg(not(target_arch = "wasm32"))]
pub mod state_trace_wire;
#[cfg(not(target_arch = "wasm32"))]
pub mod source_frontdoor_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod social_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod test_workflow;
pub mod unit_wire;
pub mod work_cost;
#[cfg(not(target_arch = "wasm32"))]
pub mod warp_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod universe_workflow;

#[cfg(feature = "wasm")]
pub mod wasm_api;
#[cfg(not(target_arch = "wasm32"))]
pub mod artifact_output;
#[cfg(not(target_arch = "wasm32"))]
pub mod docset_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod gaji_lock_workflow;
#[cfg(not(target_arch = "wasm32"))]
pub mod paths;

// Retained adapters that call a shared workflow must use the same JSON value
// identity as that workflow. This is an internal Rust API, not a public wire
// contract.
pub use serde_json;
