from __future__ import annotations

LATEST_SMOKE_SKIP_REASON_FAST_FAIL_PATH = "fast_fail_path"
LATEST_SMOKE_SKIP_REASON_FLAG_DISABLED = "flag_disabled"
LATEST_SMOKE_SKIP_REASON_PENDING_FAILURE_SUMMARY_REGENERATION = "pending_failure_summary_regeneration"
LATEST_SMOKE_SKIP_REASON_CI_GATE_RESULT_STATUS_NOT_PASS = "ci_gate_result_status_not_pass"

LATEST_SMOKE_SKIP_REASON_EXPECTED = (
    LATEST_SMOKE_SKIP_REASON_FAST_FAIL_PATH,
    LATEST_SMOKE_SKIP_REASON_FLAG_DISABLED,
    LATEST_SMOKE_SKIP_REASON_PENDING_FAILURE_SUMMARY_REGENERATION,
    LATEST_SMOKE_SKIP_REASON_CI_GATE_RESULT_STATUS_NOT_PASS,
)

