from __future__ import annotations

PROFILE_MATRIX_FULL_REAL_SMOKE_ENV_KEY = "DDN_CI_PROFILE_GATE_WITH_PROFILE_MATRIX_FULL_REAL_SMOKE"
PROFILE_MATRIX_FULL_REAL_SMOKE_STEP_TIMEOUT_ENV_KEY_CORE_LANG = (
    "DDN_CI_PROFILE_MATRIX_FULL_REAL_SMOKE_STEP_TIMEOUT_SEC_CORE_LANG"
)
PROFILE_MATRIX_FULL_REAL_SMOKE_STEP_TIMEOUT_ENV_KEY_FULL = (
    "DDN_CI_PROFILE_MATRIX_FULL_REAL_SMOKE_STEP_TIMEOUT_SEC_FULL"
)
PROFILE_MATRIX_FULL_REAL_SMOKE_STEP_TIMEOUT_ENV_KEY_SEAMGRIM = (
    "DDN_CI_PROFILE_MATRIX_FULL_REAL_SMOKE_STEP_TIMEOUT_SEC_SEAMGRIM"
)
PROFILE_MATRIX_FULL_REAL_SMOKE_STEP_TIMEOUT_DEFAULT_SEC_CORE_LANG = 900.0
PROFILE_MATRIX_FULL_REAL_SMOKE_STEP_TIMEOUT_DEFAULT_SEC_FULL = 1200.0
PROFILE_MATRIX_FULL_REAL_SMOKE_STEP_TIMEOUT_DEFAULT_SEC_SEAMGRIM = 1500.0
PROFILE_MATRIX_FULL_REAL_SMOKE_POLICY_SCHEMA = "ddn.ci.profile_matrix_full_real_smoke_policy.v1"
PROFILE_MATRIX_FULL_REAL_SMOKE_POLICY_SCRIPT = "tools/scripts/resolve_profile_matrix_full_real_smoke_policy.py"
PROFILE_MATRIX_FULL_REAL_SMOKE_CHECK_SCRIPT = "tests/run_ci_profile_matrix_full_real_smoke_check.py"
PROFILE_MATRIX_FULL_REAL_SMOKE_CHECK_SELFTEST_SCRIPT = "tests/run_ci_profile_matrix_full_real_smoke_check_selftest.py"
PROFILE_MATRIX_FULL_REAL_SMOKE_ALLOW_FLAG = "--allow-heavy-smoke"
PROFILE_MATRIX_FULL_REAL_SMOKE_SELFTEST_SCRIPT_OVERRIDE_ENV_KEY = (
    "DDN_CI_PROFILE_MATRIX_FULL_REAL_SMOKE_SELFTEST_SCRIPT_OVERRIDE"
)
PROFILE_MATRIX_FULL_REAL_SMOKE_MODE = "nightly_manual_only"
PROFILE_MATRIX_FULL_REAL_SMOKE_SCOPE_FRAGMENT = (
    f"scope={PROFILE_MATRIX_FULL_REAL_SMOKE_MODE}"
)
PROFILE_MATRIX_FULL_REAL_SMOKE_MODE_MARKER = (
    f"ci_profile_matrix_full_real_smoke_mode={PROFILE_MATRIX_FULL_REAL_SMOKE_MODE}"
)
PROFILE_MATRIX_FULL_REAL_SMOKE_STATUS_PASS = "ci_profile_matrix_full_real_smoke_status=pass"
PROFILE_MATRIX_FULL_REAL_SMOKE_FLAG = "--with-profile-matrix-full-real-smoke"
PROFILE_MATRIX_FULL_AGGREGATE_ENV_KEY = "DDN_CI_PROFILE_GATE_FULL_AGGREGATE"
PROFILE_MATRIX_FULL_REAL_SMOKE_TIMEOUT_DEFAULTS_TEXT = (
    f"core_lang:{PROFILE_MATRIX_FULL_REAL_SMOKE_STEP_TIMEOUT_DEFAULT_SEC_CORE_LANG:g},"
    f"full:{PROFILE_MATRIX_FULL_REAL_SMOKE_STEP_TIMEOUT_DEFAULT_SEC_FULL:g},"
    f"seamgrim:{PROFILE_MATRIX_FULL_REAL_SMOKE_STEP_TIMEOUT_DEFAULT_SEC_SEAMGRIM:g}"
)
PROFILE_MATRIX_SELFTEST_GATE_FLAGS_VAR = "profile_matrix_selftest_gate_flags"
PROFILE_MATRIX_SELFTEST_GATE_FLAGS_HELPER_SCRIPT = "tools/scripts/resolve_profile_matrix_selftest_gate_flags.py"
PROFILE_MATRIX_SELFTEST_GATE_FLAGS_POLICY_SCHEMA = "ddn.ci.profile_matrix_selftest_gate_flags.v1"
PROFILE_MATRIX_SELFTEST_FULL_AGGREGATE_FLAG = "--profile-matrix-selftest-full-aggregate-gates"
PROFILE_MATRIX_SELFTEST_FULL_REAL_SMOKE_FLAG = (
    "--profile-matrix-selftest-with-profile-matrix-full-real-smoke"
)
PROFILE_MATRIX_SELFTEST_GATE_TIMEOUT_DEFAULTS_FRAGMENT = (
    f"step_timeout_defaults={PROFILE_MATRIX_FULL_REAL_SMOKE_TIMEOUT_DEFAULTS_TEXT}"
)
PROFILE_MATRIX_GATE_SELFTEST_SCRIPT = "tests/run_ci_profile_matrix_gate_selftest.py"
PROFILE_MATRIX_GATE_SELFTEST_OK_MARKER = "ci profile matrix gate selftest ok"
PROFILE_MATRIX_GATE_SELFTEST_FULL_REAL_FLAG = "--full-real-profiles"
PROFILE_MATRIX_GATE_SELFTEST_REAL_PROFILES_FLAG = "--real-profiles"
PROFILE_MATRIX_GATE_SELFTEST_REAL_PROFILES = "core_lang,full,seamgrim"
PROFILE_MATRIX_GATE_SELFTEST_REAL_PROFILES_MARKER = (
    f"ci_profile_matrix_selftest_real_profiles={PROFILE_MATRIX_GATE_SELFTEST_REAL_PROFILES}"
)
PROFILE_MATRIX_GATE_SELFTEST_SKIPPED_REAL_PROFILES_MARKER = "ci_profile_matrix_selftest_skipped_real_profiles=-"
PROFILE_MATRIX_GATE_SELFTEST_LIGHTWEIGHT_FALSE_MARKER = "ci_profile_matrix_selftest_lightweight_real_profiles=false"

PROFILE_MATRIX_FULL_REAL_SMOKE_GATE_TOKENS = [
    PROFILE_MATRIX_FULL_REAL_SMOKE_ENV_KEY,
    PROFILE_MATRIX_FULL_REAL_SMOKE_CHECK_SCRIPT,
    PROFILE_MATRIX_FULL_REAL_SMOKE_ALLOW_FLAG,
    PROFILE_MATRIX_FULL_REAL_SMOKE_MODE_MARKER,
    PROFILE_MATRIX_FULL_REAL_SMOKE_STATUS_PASS,
]

PROFILE_MATRIX_GATE_SELFTEST_FULL_REAL_TOKENS = [
    PROFILE_MATRIX_GATE_SELFTEST_SCRIPT,
    PROFILE_MATRIX_GATE_SELFTEST_FULL_REAL_FLAG,
    PROFILE_MATRIX_GATE_SELFTEST_REAL_PROFILES_FLAG,
    PROFILE_MATRIX_GATE_SELFTEST_REAL_PROFILES,
    PROFILE_MATRIX_GATE_SELFTEST_REAL_PROFILES_MARKER,
    PROFILE_MATRIX_GATE_SELFTEST_SKIPPED_REAL_PROFILES_MARKER,
    PROFILE_MATRIX_GATE_SELFTEST_LIGHTWEIGHT_FALSE_MARKER,
    PROFILE_MATRIX_GATE_SELFTEST_OK_MARKER,
]

GITLAB_PROFILE_MATRIX_FULL_REAL_SMOKE_POLICY_TOKENS = [
    f'{PROFILE_MATRIX_FULL_REAL_SMOKE_ENV_KEY}: "0"',
    PROFILE_MATRIX_FULL_REAL_SMOKE_POLICY_SCRIPT,
    "--provider gitlab --format shell",
]

AZURE_PROFILE_MATRIX_FULL_REAL_SMOKE_POLICY_TOKENS = [
    f'{PROFILE_MATRIX_FULL_REAL_SMOKE_ENV_KEY}: "0"',
    PROFILE_MATRIX_FULL_REAL_SMOKE_POLICY_SCRIPT,
    "--provider azure --format shell",
]

GITLAB_PROFILE_MATRIX_SELFTEST_GATE_TOKENS = [
    f'{PROFILE_MATRIX_FULL_AGGREGATE_ENV_KEY}: "0"',
    PROFILE_MATRIX_SELFTEST_GATE_FLAGS_HELPER_SCRIPT,
    "--provider gitlab --format shell",
]

AZURE_PROFILE_MATRIX_SELFTEST_GATE_TOKENS = [
    f'{PROFILE_MATRIX_FULL_AGGREGATE_ENV_KEY}: "0"',
    PROFILE_MATRIX_SELFTEST_GATE_FLAGS_HELPER_SCRIPT,
    "--provider azure --format shell",
]
