from __future__ import annotations

from _ci_age3_completion_gate_contract import (
    AGE3_COMPLETION_GATE_CRITERIA_NAMES,
    AGE3_COMPLETION_GATE_CRITERIA_SUMMARY_KEYS,
    age3_completion_gate_criteria_summary_key,
    age3_completion_gate_criteria_sync_summary_key,
)
from _ci_aggregate_diag_specs_common import build_identity_field_specs


def _age3_criteria_snapshot_key(name: str) -> str:
    return f"age3_completion_gate_criteria_{name}_ok"


AGE3_COMPLETION_GATE_CRITERIA_SNAPSHOT_KEYS: tuple[str, ...] = tuple(
    _age3_criteria_snapshot_key(name) for name in AGE3_COMPLETION_GATE_CRITERIA_NAMES
)


CI_SANITY_DEFAULT_SNAPSHOT = {
    "status": "missing_report",
    "ok": "0",
    "code": "-",
    "step": "-",
    "profile": "full",
    "msg": "ci sanity report missing or invalid",
    "step_count": "0",
    "failed_steps": "0",
    "seamgrim_interface_boundary_ok": "0",
    "overlay_session_wired_consistency_ok": "0",
    "overlay_session_diag_parity_ok": "0",
    "overlay_compare_diag_parity_ok": "0",
    "pack_golden_lang_consistency_ok": "0",
    "pack_golden_metadata_ok": "0",
    "pack_golden_graph_export_ok": "0",
    "canon_ast_dpack_ok": "0",
    "contract_tier_unsupported_ok": "0",
    "contract_tier_age3_min_enforcement_ok": "0",
    "map_access_contract_ok": "0",
    "stdlib_catalog_ok": "0",
    "stdlib_catalog_selftest_ok": "0",
    "tensor_v0_pack_ok": "0",
    "tensor_v0_cli_ok": "0",
    "fixed64_darwin_real_report_contract_ok": "0",
    "fixed64_darwin_real_report_live_ok": "0",
    "fixed64_darwin_real_report_readiness_selftest_ok": "0",
    "fixed64_darwin_real_report_live_report_path": "-",
    "fixed64_darwin_real_report_live_report_exists": "0",
    "fixed64_darwin_real_report_live_status": "-",
    "fixed64_darwin_real_report_live_resolved_status": "-",
    "fixed64_darwin_real_report_live_resolved_source": "-",
    "fixed64_darwin_real_report_live_resolve_invalid_hit_count": "-",
    "fixed64_darwin_real_report_live_resolved_source_zip": "-",
    "fixed64_darwin_real_report_live_check_selftest_ok": "0",
    "fixed64_threeway_inputs_selftest_ok": "0",
    "registry_strict_audit_ok": "0",
    "registry_defaults_ok": "0",
    "pipeline_emit_flags_ok": "0",
    "pipeline_emit_flags_selftest_ok": "0",
    "ci_sanity_emit_artifacts_sanity_contract_selftest_ok": "0",
    "age2_completion_gate_ok": "0",
    "age2_completion_gate_selftest_ok": "0",
    "age2_close_ok": "0",
    "age2_close_selftest_ok": "0",
    "age3_completion_gate_ok": "0",
    "age3_completion_gate_selftest_ok": "0",
    "age3_close_ok": "0",
    "age3_close_selftest_ok": "0",
    "age2_completion_gate_failure_codes": "-",
    "age2_completion_gate_failure_code_count": "0",
    "age3_completion_gate_failure_codes": "-",
    "age3_completion_gate_failure_code_count": "0",
    "age3_bogae_geoul_visibility_smoke_ok": "0",
    "age3_bogae_geoul_visibility_smoke_report_path": "-",
    "age3_bogae_geoul_visibility_smoke_report_exists": "0",
    "age3_bogae_geoul_visibility_smoke_schema": "-",
    "age3_bogae_geoul_visibility_smoke_overall_ok": "0",
    "age3_bogae_geoul_visibility_smoke_checks_ok": "0",
    "age3_bogae_geoul_visibility_smoke_sim_state_hash_changes": "0",
    "age3_bogae_geoul_visibility_smoke_sim_bogae_hash_changes": "0",
    "seamgrim_wasm_web_step_check_ok": "0",
    "seamgrim_wasm_web_step_check_report_path": "-",
    "seamgrim_wasm_web_step_check_report_exists": "0",
    "seamgrim_wasm_web_step_check_schema": "-",
    "seamgrim_wasm_web_step_check_checked_files": "-",
    "seamgrim_wasm_web_step_check_missing_count": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_ok": "0",
    "ci_sanity_seamgrim_numeric_factor_policy_report_path": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_report_exists": "0",
    "ci_sanity_seamgrim_numeric_factor_policy_schema": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_text": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_bit_limit": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_pollard_iters": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_pollard_c_seeds": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_pollard_x0_seeds": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_fallback_limit": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_small_prime_max": "-",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_ok": "0",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_report_path": "-",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_report_exists": "0",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_schema": "-",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_docs_issue_count": "-",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_repo_issue_count": "-",
    "age5_combined_heavy_policy_selftest_ok": "0",
    "profile_matrix_full_real_smoke_policy_selftest_ok": "0",
    "dynamic_source_profile_split_selftest_ok": "0",
    "age5_combined_heavy_report_schema": "-",
    "age5_combined_heavy_required_reports": "-",
    "age5_combined_heavy_required_criteria": "-",
    "age5_combined_heavy_child_summary_default_fields": "-",
    "age5_combined_heavy_combined_contract_summary_fields": "-",
    "age5_combined_heavy_full_summary_contract_fields": "-",
}
for _snapshot_key in AGE3_COMPLETION_GATE_CRITERIA_SNAPSHOT_KEYS:
    CI_SANITY_DEFAULT_SNAPSHOT[_snapshot_key] = "0"

CI_SANITY_STEP_OK_SPECS = (
    ("seamgrim_interface_boundary_ok", "seamgrim_interface_boundary_contract_check"),
    ("overlay_session_wired_consistency_ok", "seamgrim_overlay_session_wired_consistency_check"),
    ("overlay_session_diag_parity_ok", "seamgrim_overlay_session_diag_parity_check"),
    ("overlay_compare_diag_parity_ok", "seamgrim_overlay_compare_diag_parity_check"),
    ("pack_golden_lang_consistency_ok", "ci_pack_golden_lang_consistency_selftest"),
    ("pack_golden_metadata_ok", "ci_pack_golden_metadata_selftest"),
    ("pack_golden_graph_export_ok", "ci_pack_golden_graph_export_selftest"),
    ("canon_ast_dpack_ok", "ci_canon_ast_dpack_selftest"),
    ("contract_tier_unsupported_ok", "contract_tier_unsupported_check"),
    ("contract_tier_age3_min_enforcement_ok", "contract_tier_age3_min_enforcement_check"),
    ("map_access_contract_ok", "map_access_contract_check"),
    ("stdlib_catalog_ok", "stdlib_catalog_check"),
    ("stdlib_catalog_selftest_ok", "stdlib_catalog_check_selftest"),
    ("tensor_v0_pack_ok", "tensor_v0_pack_check"),
    ("tensor_v0_cli_ok", "tensor_v0_cli_check"),
    ("fixed64_darwin_real_report_contract_ok", "fixed64_darwin_real_report_contract_check"),
    ("fixed64_darwin_real_report_live_ok", "fixed64_darwin_real_report_live_check"),
    (
        "fixed64_darwin_real_report_readiness_selftest_ok",
        "fixed64_darwin_real_report_readiness_check_selftest",
    ),
    ("registry_strict_audit_ok", "gaji_registry_strict_audit_check"),
    ("registry_defaults_ok", "gaji_registry_defaults_check"),
    ("age2_completion_gate_ok", "age2_completion_gate"),
    ("age2_completion_gate_selftest_ok", "age2_completion_gate_selftest"),
    ("age2_close_ok", "age2_close"),
    ("age2_close_selftest_ok", "age2_close_selftest"),
    ("age3_completion_gate_ok", "age3_completion_gate"),
    ("age3_completion_gate_selftest_ok", "age3_completion_gate_selftest"),
    ("age3_close_ok", "age3_close"),
    ("age3_close_selftest_ok", "age3_close_selftest"),
)
CI_SANITY_SNAPSHOT_FIELD_SPECS = build_identity_field_specs(
    "status",
    "ok",
    "code",
    "step",
    "profile",
    "msg",
    "step_count",
    "failed_steps",
    "ci_sanity_emit_artifacts_sanity_contract_selftest_ok",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_ok",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_report_path",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_report_exists",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_schema",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_docs_issue_count",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_repo_issue_count",
    "ci_sanity_seamgrim_numeric_factor_policy_ok",
    "ci_sanity_seamgrim_numeric_factor_policy_report_path",
    "ci_sanity_seamgrim_numeric_factor_policy_report_exists",
    "ci_sanity_seamgrim_numeric_factor_policy_schema",
    "ci_sanity_seamgrim_numeric_factor_policy_text",
    "ci_sanity_seamgrim_numeric_factor_policy_bit_limit",
    "ci_sanity_seamgrim_numeric_factor_policy_pollard_iters",
    "ci_sanity_seamgrim_numeric_factor_policy_pollard_c_seeds",
    "ci_sanity_seamgrim_numeric_factor_policy_pollard_x0_seeds",
    "ci_sanity_seamgrim_numeric_factor_policy_fallback_limit",
    "ci_sanity_seamgrim_numeric_factor_policy_small_prime_max",
)
CI_SANITY_SUMMARY_LINE_SPECS = (
    ("ci_sanity_gate_status", "status"),
    ("ci_sanity_gate_ok", "ok"),
    ("ci_sanity_gate_code", "code"),
    ("ci_sanity_gate_step", "step"),
    ("ci_sanity_gate_profile", "profile"),
    ("ci_sanity_gate_msg", "msg"),
    ("ci_sanity_gate_step_count", "step_count"),
    ("ci_sanity_gate_failed_steps", "failed_steps"),
    ("ci_sanity_seamgrim_interface_boundary_ok", "seamgrim_interface_boundary_ok"),
    ("ci_sanity_overlay_session_wired_consistency_ok", "overlay_session_wired_consistency_ok"),
    ("ci_sanity_overlay_session_diag_parity_ok", "overlay_session_diag_parity_ok"),
    ("ci_sanity_overlay_compare_diag_parity_ok", "overlay_compare_diag_parity_ok"),
    ("ci_sanity_pack_golden_lang_consistency_ok", "pack_golden_lang_consistency_ok"),
    ("ci_sanity_pack_golden_metadata_ok", "pack_golden_metadata_ok"),
    ("ci_sanity_pack_golden_graph_export_ok", "pack_golden_graph_export_ok"),
    ("ci_sanity_canon_ast_dpack_ok", "canon_ast_dpack_ok"),
    ("ci_sanity_contract_tier_unsupported_ok", "contract_tier_unsupported_ok"),
    ("ci_sanity_contract_tier_age3_min_enforcement_ok", "contract_tier_age3_min_enforcement_ok"),
    ("ci_sanity_map_access_contract_ok", "map_access_contract_ok"),
    ("ci_sanity_stdlib_catalog_ok", "stdlib_catalog_ok"),
    ("ci_sanity_stdlib_catalog_selftest_ok", "stdlib_catalog_selftest_ok"),
    ("ci_sanity_tensor_v0_pack_ok", "tensor_v0_pack_ok"),
    ("ci_sanity_tensor_v0_cli_ok", "tensor_v0_cli_ok"),
    ("ci_sanity_fixed64_darwin_real_report_contract_ok", "fixed64_darwin_real_report_contract_ok"),
    ("ci_sanity_fixed64_darwin_real_report_live_ok", "fixed64_darwin_real_report_live_ok"),
    (
        "ci_sanity_fixed64_darwin_real_report_readiness_selftest_ok",
        "fixed64_darwin_real_report_readiness_selftest_ok",
    ),
    (
        "ci_sanity_fixed64_darwin_real_report_live_report_path",
        "fixed64_darwin_real_report_live_report_path",
    ),
    (
        "ci_sanity_fixed64_darwin_real_report_live_report_exists",
        "fixed64_darwin_real_report_live_report_exists",
    ),
    (
        "ci_sanity_fixed64_darwin_real_report_live_status",
        "fixed64_darwin_real_report_live_status",
    ),
    (
        "ci_sanity_fixed64_darwin_real_report_live_resolved_status",
        "fixed64_darwin_real_report_live_resolved_status",
    ),
    (
        "ci_sanity_fixed64_darwin_real_report_live_resolved_source",
        "fixed64_darwin_real_report_live_resolved_source",
    ),
    (
        "ci_sanity_fixed64_darwin_real_report_live_resolve_invalid_hit_count",
        "fixed64_darwin_real_report_live_resolve_invalid_hit_count",
    ),
    (
        "ci_sanity_fixed64_darwin_real_report_live_resolved_source_zip",
        "fixed64_darwin_real_report_live_resolved_source_zip",
    ),
    (
        "ci_sanity_fixed64_darwin_real_report_live_check_selftest_ok",
        "fixed64_darwin_real_report_live_check_selftest_ok",
    ),
    (
        "ci_sanity_fixed64_threeway_inputs_selftest_ok",
        "fixed64_threeway_inputs_selftest_ok",
    ),
    ("ci_sanity_registry_strict_audit_ok", "registry_strict_audit_ok"),
    ("ci_sanity_registry_defaults_ok", "registry_defaults_ok"),
    ("ci_sanity_pipeline_emit_flags_ok", "pipeline_emit_flags_ok"),
    ("ci_sanity_pipeline_emit_flags_selftest_ok", "pipeline_emit_flags_selftest_ok"),
    (
        "ci_sanity_emit_artifacts_sanity_contract_selftest_ok",
        "ci_sanity_emit_artifacts_sanity_contract_selftest_ok",
    ),
    ("ci_sanity_age2_completion_gate_ok", "age2_completion_gate_ok"),
    ("ci_sanity_age2_completion_gate_selftest_ok", "age2_completion_gate_selftest_ok"),
    ("ci_sanity_age2_close_ok", "age2_close_ok"),
    ("ci_sanity_age2_close_selftest_ok", "age2_close_selftest_ok"),
    ("ci_sanity_age3_completion_gate_ok", "age3_completion_gate_ok"),
    ("ci_sanity_age3_completion_gate_selftest_ok", "age3_completion_gate_selftest_ok"),
    ("ci_sanity_age3_close_ok", "age3_close_ok"),
    ("ci_sanity_age3_close_selftest_ok", "age3_close_selftest_ok"),
    ("ci_sanity_age2_completion_gate_failure_codes", "age2_completion_gate_failure_codes"),
    ("ci_sanity_age2_completion_gate_failure_code_count", "age2_completion_gate_failure_code_count"),
    ("ci_sanity_age3_completion_gate_failure_codes", "age3_completion_gate_failure_codes"),
    ("ci_sanity_age3_completion_gate_failure_code_count", "age3_completion_gate_failure_code_count"),
    ("ci_sanity_age3_bogae_geoul_visibility_smoke_ok", "age3_bogae_geoul_visibility_smoke_ok"),
    (
        "ci_sanity_age3_bogae_geoul_visibility_smoke_report_path",
        "age3_bogae_geoul_visibility_smoke_report_path",
    ),
    (
        "ci_sanity_age3_bogae_geoul_visibility_smoke_report_exists",
        "age3_bogae_geoul_visibility_smoke_report_exists",
    ),
    (
        "ci_sanity_age3_bogae_geoul_visibility_smoke_schema",
        "age3_bogae_geoul_visibility_smoke_schema",
    ),
    (
        "ci_sanity_age3_bogae_geoul_visibility_smoke_overall_ok",
        "age3_bogae_geoul_visibility_smoke_overall_ok",
    ),
    (
        "ci_sanity_age3_bogae_geoul_visibility_smoke_checks_ok",
        "age3_bogae_geoul_visibility_smoke_checks_ok",
    ),
    (
        "ci_sanity_age3_bogae_geoul_visibility_smoke_sim_state_hash_changes",
        "age3_bogae_geoul_visibility_smoke_sim_state_hash_changes",
    ),
    (
        "ci_sanity_age3_bogae_geoul_visibility_smoke_sim_bogae_hash_changes",
        "age3_bogae_geoul_visibility_smoke_sim_bogae_hash_changes",
    ),
    (
        "ci_sanity_seamgrim_wasm_web_step_check_ok",
        "seamgrim_wasm_web_step_check_ok",
    ),
    (
        "ci_sanity_seamgrim_wasm_web_step_check_report_path",
        "seamgrim_wasm_web_step_check_report_path",
    ),
    (
        "ci_sanity_seamgrim_wasm_web_step_check_report_exists",
        "seamgrim_wasm_web_step_check_report_exists",
    ),
    (
        "ci_sanity_seamgrim_wasm_web_step_check_schema",
        "seamgrim_wasm_web_step_check_schema",
    ),
    (
        "ci_sanity_seamgrim_wasm_web_step_check_checked_files",
        "seamgrim_wasm_web_step_check_checked_files",
    ),
    (
        "ci_sanity_seamgrim_wasm_web_step_check_missing_count",
        "seamgrim_wasm_web_step_check_missing_count",
    ),
    (
        "ci_sanity_seamgrim_numeric_factor_policy_ok",
        "ci_sanity_seamgrim_numeric_factor_policy_ok",
    ),
    (
        "ci_sanity_seamgrim_numeric_factor_policy_report_path",
        "ci_sanity_seamgrim_numeric_factor_policy_report_path",
    ),
    (
        "ci_sanity_seamgrim_numeric_factor_policy_report_exists",
        "ci_sanity_seamgrim_numeric_factor_policy_report_exists",
    ),
    (
        "ci_sanity_seamgrim_numeric_factor_policy_schema",
        "ci_sanity_seamgrim_numeric_factor_policy_schema",
    ),
    (
        "ci_sanity_seamgrim_numeric_factor_policy_text",
        "ci_sanity_seamgrim_numeric_factor_policy_text",
    ),
    (
        "ci_sanity_seamgrim_numeric_factor_policy_bit_limit",
        "ci_sanity_seamgrim_numeric_factor_policy_bit_limit",
    ),
    (
        "ci_sanity_seamgrim_numeric_factor_policy_pollard_iters",
        "ci_sanity_seamgrim_numeric_factor_policy_pollard_iters",
    ),
    (
        "ci_sanity_seamgrim_numeric_factor_policy_pollard_c_seeds",
        "ci_sanity_seamgrim_numeric_factor_policy_pollard_c_seeds",
    ),
    (
        "ci_sanity_seamgrim_numeric_factor_policy_pollard_x0_seeds",
        "ci_sanity_seamgrim_numeric_factor_policy_pollard_x0_seeds",
    ),
    (
        "ci_sanity_seamgrim_numeric_factor_policy_fallback_limit",
        "ci_sanity_seamgrim_numeric_factor_policy_fallback_limit",
    ),
    (
        "ci_sanity_seamgrim_numeric_factor_policy_small_prime_max",
        "ci_sanity_seamgrim_numeric_factor_policy_small_prime_max",
    ),
    (
        "ci_sanity_seamgrim_pack_evidence_tier_runner_ok",
        "ci_sanity_seamgrim_pack_evidence_tier_runner_ok",
    ),
    (
        "ci_sanity_seamgrim_pack_evidence_tier_runner_report_path",
        "ci_sanity_seamgrim_pack_evidence_tier_runner_report_path",
    ),
    (
        "ci_sanity_seamgrim_pack_evidence_tier_runner_report_exists",
        "ci_sanity_seamgrim_pack_evidence_tier_runner_report_exists",
    ),
    (
        "ci_sanity_seamgrim_pack_evidence_tier_runner_schema",
        "ci_sanity_seamgrim_pack_evidence_tier_runner_schema",
    ),
    (
        "ci_sanity_seamgrim_pack_evidence_tier_runner_docs_issue_count",
        "ci_sanity_seamgrim_pack_evidence_tier_runner_docs_issue_count",
    ),
    (
        "ci_sanity_seamgrim_pack_evidence_tier_runner_repo_issue_count",
        "ci_sanity_seamgrim_pack_evidence_tier_runner_repo_issue_count",
    ),
    ("ci_sanity_age5_combined_heavy_policy_selftest_ok", "age5_combined_heavy_policy_selftest_ok"),
    (
        "ci_sanity_profile_matrix_full_real_smoke_policy_selftest_ok",
        "profile_matrix_full_real_smoke_policy_selftest_ok",
    ),
    (
        "ci_sanity_dynamic_source_profile_split_selftest_ok",
        "dynamic_source_profile_split_selftest_ok",
    ),
    ("ci_sanity_age5_combined_heavy_report_schema", "age5_combined_heavy_report_schema"),
    ("ci_sanity_age5_combined_heavy_required_reports", "age5_combined_heavy_required_reports"),
    ("ci_sanity_age5_combined_heavy_required_criteria", "age5_combined_heavy_required_criteria"),
    (
        "ci_sanity_age5_combined_heavy_child_summary_default_fields",
        "age5_combined_heavy_child_summary_default_fields",
    ),
    (
        "ci_sanity_age5_combined_heavy_combined_contract_summary_fields",
        "age5_combined_heavy_combined_contract_summary_fields",
    ),
    (
        "ci_sanity_age5_combined_heavy_full_summary_contract_fields",
        "age5_combined_heavy_full_summary_contract_fields",
    ),
)
CI_SANITY_SUMMARY_LINE_SPECS = CI_SANITY_SUMMARY_LINE_SPECS + tuple(
    (
        age3_completion_gate_criteria_summary_key(criteria_name),
        _age3_criteria_snapshot_key(criteria_name),
    )
    for criteria_name in AGE3_COMPLETION_GATE_CRITERIA_NAMES
)

CI_SYNC_READINESS_DEFAULT_SNAPSHOT = {
    "status": "missing_report",
    "ok": "0",
    "code": "-",
    "step": "-",
    "sanity_profile": "full",
    "msg": "ci sync readiness report missing or invalid",
    "step_count": "0",
    "ci_sanity_pipeline_emit_flags_ok": "0",
    "ci_sanity_pipeline_emit_flags_selftest_ok": "0",
    "ci_sanity_emit_artifacts_sanity_contract_selftest_ok": "0",
    "ci_sync_readiness_ci_sanity_emit_artifacts_sanity_contract_selftest_ok": "0",
    "ci_sanity_pack_golden_graph_export_ok": "0",
    "ci_sync_readiness_ci_sanity_pack_golden_graph_export_ok": "0",
    "ci_sanity_age2_completion_gate_ok": "0",
    "ci_sanity_age2_completion_gate_selftest_ok": "0",
    "ci_sanity_age2_close_ok": "0",
    "ci_sanity_age2_close_selftest_ok": "0",
    "ci_sanity_age3_completion_gate_ok": "0",
    "ci_sanity_age3_completion_gate_selftest_ok": "0",
    "ci_sanity_age3_close_ok": "0",
    "ci_sanity_age3_close_selftest_ok": "0",
    "ci_sanity_age2_completion_gate_failure_codes": "-",
    "ci_sanity_age2_completion_gate_failure_code_count": "0",
    "ci_sanity_age3_completion_gate_failure_codes": "-",
    "ci_sanity_age3_completion_gate_failure_code_count": "0",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_ok": "0",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_report_path": "-",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_report_exists": "0",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_schema": "-",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_overall_ok": "0",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_checks_ok": "0",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_sim_state_hash_changes": "0",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_sim_bogae_hash_changes": "0",
    "ci_sanity_seamgrim_wasm_web_step_check_ok": "0",
    "ci_sanity_seamgrim_wasm_web_step_check_report_path": "-",
    "ci_sanity_seamgrim_wasm_web_step_check_report_exists": "0",
    "ci_sanity_seamgrim_wasm_web_step_check_schema": "-",
    "ci_sanity_seamgrim_wasm_web_step_check_checked_files": "-",
    "ci_sanity_seamgrim_wasm_web_step_check_missing_count": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_ok": "0",
    "ci_sanity_seamgrim_numeric_factor_policy_report_path": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_report_exists": "0",
    "ci_sanity_seamgrim_numeric_factor_policy_schema": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_text": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_bit_limit": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_pollard_iters": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_pollard_c_seeds": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_pollard_x0_seeds": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_fallback_limit": "-",
    "ci_sanity_seamgrim_numeric_factor_policy_small_prime_max": "-",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_ok": "0",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_report_path": "-",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_report_exists": "0",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_schema": "-",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_docs_issue_count": "-",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_repo_issue_count": "-",
    "ci_sanity_fixed64_darwin_real_report_live_report_path": "-",
    "ci_sanity_fixed64_darwin_real_report_live_report_exists": "0",
    "ci_sanity_fixed64_darwin_real_report_live_status": "-",
    "ci_sanity_fixed64_darwin_real_report_live_resolved_status": "-",
    "ci_sanity_fixed64_darwin_real_report_live_resolved_source": "-",
    "ci_sanity_fixed64_darwin_real_report_live_resolve_invalid_hit_count": "-",
    "ci_sanity_fixed64_darwin_real_report_live_resolved_source_zip": "-",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_report_path": "-",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_report_exists": "0",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_status": "-",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_status": "-",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_source": "-",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolve_invalid_hit_count": "-",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_source_zip": "-",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_check_selftest_ok": "0",
    "ci_sync_readiness_ci_sanity_fixed64_threeway_inputs_selftest_ok": "0",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_ok": "0",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_report_path": "-",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_report_exists": "0",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_schema": "-",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_overall_ok": "0",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_checks_ok": "0",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_sim_state_hash_changes": "0",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_sim_bogae_hash_changes": "0",
    "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_ok": "0",
    "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_report_path": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_report_exists": "0",
    "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_schema": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_checked_files": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_missing_count": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_ok": "0",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_report_path": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_report_exists": "0",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_schema": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_text": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_bit_limit": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_pollard_iters": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_pollard_c_seeds": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_pollard_x0_seeds": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_fallback_limit": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_small_prime_max": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_ok": "0",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_report_path": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_report_exists": "0",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_schema": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_docs_issue_count": "-",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_repo_issue_count": "-",
    "ci_sync_readiness_ci_sanity_age2_completion_gate_failure_codes": "-",
    "ci_sync_readiness_ci_sanity_age2_completion_gate_failure_code_count": "0",
    "ci_sync_readiness_ci_sanity_age3_completion_gate_failure_codes": "-",
    "ci_sync_readiness_ci_sanity_age3_completion_gate_failure_code_count": "0",
    "ci_sanity_age5_combined_heavy_policy_selftest_ok": "0",
    "ci_sanity_profile_matrix_full_real_smoke_policy_selftest_ok": "0",
    "ci_sanity_dynamic_source_profile_split_selftest_ok": "0",
    "ci_sanity_age5_combined_heavy_report_schema": "-",
    "ci_sanity_age5_combined_heavy_required_reports": "-",
    "ci_sanity_age5_combined_heavy_required_criteria": "-",
    "ci_sanity_age5_combined_heavy_child_summary_default_fields": "-",
    "ci_sanity_age5_combined_heavy_combined_contract_summary_fields": "-",
    "ci_sanity_age5_combined_heavy_full_summary_contract_fields": "-",
}
for _criteria_name in AGE3_COMPLETION_GATE_CRITERIA_NAMES:
    CI_SYNC_READINESS_DEFAULT_SNAPSHOT[age3_completion_gate_criteria_summary_key(_criteria_name)] = "0"
    CI_SYNC_READINESS_DEFAULT_SNAPSHOT[
        age3_completion_gate_criteria_sync_summary_key(_criteria_name)
    ] = "0"

CI_SYNC_READINESS_SNAPSHOT_FIELD_SPECS = build_identity_field_specs(
    "status",
    "ok",
    "code",
    "step",
    "sanity_profile",
    "msg",
    "step_count",
    "ci_sanity_pipeline_emit_flags_ok",
    "ci_sanity_pipeline_emit_flags_selftest_ok",
    "ci_sanity_emit_artifacts_sanity_contract_selftest_ok",
    "ci_sync_readiness_ci_sanity_emit_artifacts_sanity_contract_selftest_ok",
    "ci_sanity_pack_golden_graph_export_ok",
    "ci_sync_readiness_ci_sanity_pack_golden_graph_export_ok",
    "ci_sanity_age2_completion_gate_ok",
    "ci_sanity_age2_completion_gate_selftest_ok",
    "ci_sanity_age2_close_ok",
    "ci_sanity_age2_close_selftest_ok",
    "ci_sanity_age3_completion_gate_ok",
    "ci_sanity_age3_completion_gate_selftest_ok",
    "ci_sanity_age3_close_ok",
    "ci_sanity_age3_close_selftest_ok",
    "ci_sanity_age2_completion_gate_failure_codes",
    "ci_sanity_age2_completion_gate_failure_code_count",
    "ci_sanity_age3_completion_gate_failure_codes",
    "ci_sanity_age3_completion_gate_failure_code_count",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_ok",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_report_path",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_report_exists",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_schema",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_overall_ok",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_checks_ok",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_sim_state_hash_changes",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_sim_bogae_hash_changes",
    "ci_sanity_seamgrim_wasm_web_step_check_ok",
    "ci_sanity_seamgrim_wasm_web_step_check_report_path",
    "ci_sanity_seamgrim_wasm_web_step_check_report_exists",
    "ci_sanity_seamgrim_wasm_web_step_check_schema",
    "ci_sanity_seamgrim_wasm_web_step_check_checked_files",
    "ci_sanity_seamgrim_wasm_web_step_check_missing_count",
    "ci_sanity_seamgrim_numeric_factor_policy_ok",
    "ci_sanity_seamgrim_numeric_factor_policy_report_path",
    "ci_sanity_seamgrim_numeric_factor_policy_report_exists",
    "ci_sanity_seamgrim_numeric_factor_policy_schema",
    "ci_sanity_seamgrim_numeric_factor_policy_text",
    "ci_sanity_seamgrim_numeric_factor_policy_bit_limit",
    "ci_sanity_seamgrim_numeric_factor_policy_pollard_iters",
    "ci_sanity_seamgrim_numeric_factor_policy_pollard_c_seeds",
    "ci_sanity_seamgrim_numeric_factor_policy_pollard_x0_seeds",
    "ci_sanity_seamgrim_numeric_factor_policy_fallback_limit",
    "ci_sanity_seamgrim_numeric_factor_policy_small_prime_max",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_ok",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_report_path",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_report_exists",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_schema",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_docs_issue_count",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_repo_issue_count",
    "ci_sanity_fixed64_darwin_real_report_live_report_path",
    "ci_sanity_fixed64_darwin_real_report_live_report_exists",
    "ci_sanity_fixed64_darwin_real_report_live_status",
    "ci_sanity_fixed64_darwin_real_report_live_resolved_status",
    "ci_sanity_fixed64_darwin_real_report_live_resolved_source",
    "ci_sanity_fixed64_darwin_real_report_live_resolve_invalid_hit_count",
    "ci_sanity_fixed64_darwin_real_report_live_resolved_source_zip",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_report_path",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_report_exists",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_status",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_status",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_source",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolve_invalid_hit_count",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_source_zip",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_check_selftest_ok",
    "ci_sync_readiness_ci_sanity_fixed64_threeway_inputs_selftest_ok",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_ok",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_report_path",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_report_exists",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_schema",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_overall_ok",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_checks_ok",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_sim_state_hash_changes",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_sim_bogae_hash_changes",
    "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_ok",
    "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_report_path",
    "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_report_exists",
    "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_schema",
    "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_checked_files",
    "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_missing_count",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_ok",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_report_path",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_report_exists",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_schema",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_text",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_bit_limit",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_pollard_iters",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_pollard_c_seeds",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_pollard_x0_seeds",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_fallback_limit",
    "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_small_prime_max",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_ok",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_report_path",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_report_exists",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_schema",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_docs_issue_count",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_repo_issue_count",
    "ci_sync_readiness_ci_sanity_age2_completion_gate_failure_codes",
    "ci_sync_readiness_ci_sanity_age2_completion_gate_failure_code_count",
    "ci_sync_readiness_ci_sanity_age3_completion_gate_failure_codes",
    "ci_sync_readiness_ci_sanity_age3_completion_gate_failure_code_count",
    "ci_sanity_age5_combined_heavy_policy_selftest_ok",
    "ci_sanity_profile_matrix_full_real_smoke_policy_selftest_ok",
    "ci_sanity_dynamic_source_profile_split_selftest_ok",
    "ci_sanity_age5_combined_heavy_report_schema",
    "ci_sanity_age5_combined_heavy_required_reports",
    "ci_sanity_age5_combined_heavy_required_criteria",
    "ci_sanity_age5_combined_heavy_child_summary_default_fields",
    "ci_sanity_age5_combined_heavy_combined_contract_summary_fields",
    "ci_sanity_age5_combined_heavy_full_summary_contract_fields",
)
CI_SYNC_READINESS_SNAPSHOT_FIELD_SPECS = CI_SYNC_READINESS_SNAPSHOT_FIELD_SPECS + build_identity_field_specs(
    *AGE3_COMPLETION_GATE_CRITERIA_SUMMARY_KEYS,
    *tuple(age3_completion_gate_criteria_sync_summary_key(name) for name in AGE3_COMPLETION_GATE_CRITERIA_NAMES),
)
CI_SYNC_READINESS_SUMMARY_LINE_SPECS = (
    ("ci_sync_readiness_status", "status"),
    ("ci_sync_readiness_ok", "ok"),
    ("ci_sync_readiness_code", "code"),
    ("ci_sync_readiness_step", "step"),
    ("ci_sync_readiness_sanity_profile", "sanity_profile"),
    ("ci_sync_readiness_msg", "msg"),
    ("ci_sync_readiness_step_count", "step_count"),
    ("ci_sync_readiness_ci_sanity_pipeline_emit_flags_ok", "ci_sanity_pipeline_emit_flags_ok"),
    ("ci_sync_readiness_ci_sanity_pipeline_emit_flags_selftest_ok", "ci_sanity_pipeline_emit_flags_selftest_ok"),
    (
        "ci_sync_readiness_ci_sanity_emit_artifacts_sanity_contract_selftest_ok",
        "ci_sync_readiness_ci_sanity_emit_artifacts_sanity_contract_selftest_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_pack_golden_graph_export_ok",
        "ci_sync_readiness_ci_sanity_pack_golden_graph_export_ok",
    ),
    ("ci_sync_readiness_ci_sanity_age2_completion_gate_ok", "ci_sanity_age2_completion_gate_ok"),
    (
        "ci_sync_readiness_ci_sanity_age2_completion_gate_selftest_ok",
        "ci_sanity_age2_completion_gate_selftest_ok",
    ),
    ("ci_sync_readiness_ci_sanity_age2_close_ok", "ci_sanity_age2_close_ok"),
    (
        "ci_sync_readiness_ci_sanity_age2_close_selftest_ok",
        "ci_sanity_age2_close_selftest_ok",
    ),
    ("ci_sync_readiness_ci_sanity_age3_completion_gate_ok", "ci_sanity_age3_completion_gate_ok"),
    (
        "ci_sync_readiness_ci_sanity_age3_completion_gate_selftest_ok",
        "ci_sanity_age3_completion_gate_selftest_ok",
    ),
    ("ci_sync_readiness_ci_sanity_age3_close_ok", "ci_sanity_age3_close_ok"),
    (
        "ci_sync_readiness_ci_sanity_age3_close_selftest_ok",
        "ci_sanity_age3_close_selftest_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_age2_completion_gate_failure_codes",
        "ci_sync_readiness_ci_sanity_age2_completion_gate_failure_codes",
    ),
    (
        "ci_sync_readiness_ci_sanity_age2_completion_gate_failure_code_count",
        "ci_sync_readiness_ci_sanity_age2_completion_gate_failure_code_count",
    ),
    (
        "ci_sync_readiness_ci_sanity_age3_completion_gate_failure_codes",
        "ci_sync_readiness_ci_sanity_age3_completion_gate_failure_codes",
    ),
    (
        "ci_sync_readiness_ci_sanity_age3_completion_gate_failure_code_count",
        "ci_sync_readiness_ci_sanity_age3_completion_gate_failure_code_count",
    ),
    (
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_ok",
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_report_path",
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_report_path",
    ),
    (
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_report_exists",
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_report_exists",
    ),
    (
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_schema",
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_schema",
    ),
    (
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_overall_ok",
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_overall_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_checks_ok",
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_checks_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_sim_state_hash_changes",
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_sim_state_hash_changes",
    ),
    (
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_sim_bogae_hash_changes",
        "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_sim_bogae_hash_changes",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_ok",
        "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_report_path",
        "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_report_path",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_report_exists",
        "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_report_exists",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_schema",
        "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_schema",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_checked_files",
        "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_checked_files",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_missing_count",
        "ci_sync_readiness_ci_sanity_seamgrim_wasm_web_step_check_missing_count",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_ok",
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_report_path",
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_report_path",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_report_exists",
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_report_exists",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_schema",
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_schema",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_text",
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_text",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_bit_limit",
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_bit_limit",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_pollard_iters",
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_pollard_iters",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_pollard_c_seeds",
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_pollard_c_seeds",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_pollard_x0_seeds",
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_pollard_x0_seeds",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_fallback_limit",
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_fallback_limit",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_small_prime_max",
        "ci_sync_readiness_ci_sanity_seamgrim_numeric_factor_policy_small_prime_max",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_ok",
        "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_report_path",
        "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_report_path",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_report_exists",
        "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_report_exists",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_schema",
        "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_schema",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_docs_issue_count",
        "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_docs_issue_count",
    ),
    (
        "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_repo_issue_count",
        "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_repo_issue_count",
    ),
    (
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_report_path",
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_report_path",
    ),
    (
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_report_exists",
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_report_exists",
    ),
    (
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_status",
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_status",
    ),
    (
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_status",
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_status",
    ),
    (
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_source",
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_source",
    ),
    (
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolve_invalid_hit_count",
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolve_invalid_hit_count",
    ),
    (
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_source_zip",
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_source_zip",
    ),
    (
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_check_selftest_ok",
        "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_check_selftest_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_fixed64_threeway_inputs_selftest_ok",
        "ci_sync_readiness_ci_sanity_fixed64_threeway_inputs_selftest_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_age5_combined_heavy_policy_selftest_ok",
        "ci_sanity_age5_combined_heavy_policy_selftest_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_profile_matrix_full_real_smoke_policy_selftest_ok",
        "ci_sanity_profile_matrix_full_real_smoke_policy_selftest_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_dynamic_source_profile_split_selftest_ok",
        "ci_sanity_dynamic_source_profile_split_selftest_ok",
    ),
    (
        "ci_sync_readiness_ci_sanity_age5_combined_heavy_report_schema",
        "ci_sanity_age5_combined_heavy_report_schema",
    ),
    (
        "ci_sync_readiness_ci_sanity_age5_combined_heavy_required_reports",
        "ci_sanity_age5_combined_heavy_required_reports",
    ),
    (
        "ci_sync_readiness_ci_sanity_age5_combined_heavy_required_criteria",
        "ci_sanity_age5_combined_heavy_required_criteria",
    ),
    (
        "ci_sync_readiness_ci_sanity_age5_combined_heavy_child_summary_default_fields",
        "ci_sanity_age5_combined_heavy_child_summary_default_fields",
    ),
    (
        "ci_sync_readiness_ci_sanity_age5_combined_heavy_combined_contract_summary_fields",
        "ci_sanity_age5_combined_heavy_combined_contract_summary_fields",
    ),
    (
        "ci_sync_readiness_ci_sanity_age5_combined_heavy_full_summary_contract_fields",
        "ci_sanity_age5_combined_heavy_full_summary_contract_fields",
    ),
)
CI_SYNC_READINESS_SUMMARY_LINE_SPECS = CI_SYNC_READINESS_SUMMARY_LINE_SPECS + tuple(
    (
        age3_completion_gate_criteria_summary_key(criteria_name),
        age3_completion_gate_criteria_summary_key(criteria_name),
    )
    for criteria_name in AGE3_COMPLETION_GATE_CRITERIA_NAMES
) + tuple(
    (
        age3_completion_gate_criteria_sync_summary_key(criteria_name),
        age3_completion_gate_criteria_sync_summary_key(criteria_name),
    )
    for criteria_name in AGE3_COMPLETION_GATE_CRITERIA_NAMES
)

FIXED64_THREEWAY_DEFAULT_SNAPSHOT = {
    "status": "missing_report",
    "ok": "0",
    "reason": "report missing or invalid",
}
FIXED64_THREEWAY_SNAPSHOT_FIELD_SPECS = build_identity_field_specs("status", "ok", "reason")
FIXED64_THREEWAY_SUMMARY_LINE_SPECS = (
    ("fixed64_threeway_status", "status"),
    ("fixed64_threeway_ok", "ok"),
    ("fixed64_threeway_reason", "reason"),
)
