#!/usr/bin/env python
from __future__ import annotations

import sys
from pathlib import Path

TOOLS_SCRIPTS_DIR = Path(__file__).resolve().parents[1] / "tools" / "scripts"
if str(TOOLS_SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_SCRIPTS_DIR))

from ci_verify_codes import SUMMARY_VERIFY_CODES


EMIT_ARTIFACTS_CODES = {
    "REPORT_DIR_MISSING": "E_REPORT_DIR_MISSING",
    "INDEX_NOT_FOUND": "E_INDEX_NOT_FOUND",
    "INDEX_REPORTS_MISSING": "E_INDEX_REPORTS_MISSING",
    "INDEX_REPORT_KEY_MISSING": "E_INDEX_REPORT_KEY_MISSING",
    "INDEX_RESULT_PATH_MISSING": "E_INDEX_RESULT_PATH_MISSING",
    "INDEX_SUMMARY_PATH_MISSING": "E_INDEX_SUMMARY_PATH_MISSING",
    "INDEX_BRIEF_PATH_MISSING": "E_INDEX_BRIEF_PATH_MISSING",
    "INDEX_TRIAGE_PATH_MISSING": "E_INDEX_TRIAGE_PATH_MISSING",
    "RESULT_JSON_INVALID": "E_RESULT_JSON_INVALID",
    "RESULT_SCHEMA_MISMATCH": "E_RESULT_SCHEMA_MISMATCH",
    "RESULT_STATUS_UNSUPPORTED": "E_RESULT_STATUS_UNSUPPORTED",
    "RESULT_FAILED_STEPS_TYPE": "E_RESULT_FAILED_STEPS_TYPE",
    "RESULT_FAILED_STEPS_NEGATIVE": "E_RESULT_FAILED_STEPS_NEGATIVE",
    "RESULT_PASS_FAILED_STEPS": "E_RESULT_PASS_FAILED_STEPS",
    "RESULT_FAIL_FAILED_STEPS": "E_RESULT_FAIL_FAILED_STEPS",
    "SUMMARY_STATUS_MISMATCH": "E_SUMMARY_STATUS_MISMATCH",
    "BRIEF_REQUIRED_MISSING": "E_BRIEF_REQUIRED_MISSING",
    "TRIAGE_REQUIRED_MISSING": "E_TRIAGE_REQUIRED_MISSING",
}


FAILURE_SUMMARY_CODES = {
    "SUMMARY_MISSING": "E_SUMMARY_MISSING",
    "INDEX_INVALID": "E_INDEX_INVALID",
    "STATUS_HEADER_MISSING": "E_STATUS_HEADER_MISSING",
    "REQUIRE_PASS": "E_REQUIRE_PASS",
    "DETAIL_FORMAT_INVALID": "E_DETAIL_FORMAT_INVALID",
    "LOGS_FORMAT_INVALID": "E_LOGS_FORMAT_INVALID",
    "PASS_FAILED_STEPS_NOT_NONE": "E_PASS_FAILED_STEPS_NOT_NONE",
    "PASS_HAS_DETAIL": "E_PASS_HAS_DETAIL",
    "PASS_HAS_LOGS": "E_PASS_HAS_LOGS",
    "FAIL_FAILED_STEPS_EMPTY": "E_FAIL_FAILED_STEPS_EMPTY",
    "FAIL_FAILED_STEPS_PARSE_EMPTY": "E_FAIL_FAILED_STEPS_PARSE_EMPTY",
    "FAIL_FAILED_STEPS_DUPLICATE": "E_FAIL_FAILED_STEPS_DUPLICATE",
    "FAIL_DETAIL_MISSING": "E_FAIL_DETAIL_MISSING",
    "FAIL_DETAIL_DUPLICATE": "E_FAIL_DETAIL_DUPLICATE",
    "FAIL_DETAIL_NOT_IN_FAILED_STEPS": "E_FAIL_DETAIL_NOT_IN_FAILED_STEPS",
    "FAIL_DETAIL_MISSING_FOR_STEP": "E_FAIL_DETAIL_MISSING_FOR_STEP",
    "FAIL_DETAIL_RC_ZERO": "E_FAIL_DETAIL_RC_ZERO",
    "FAIL_DETAIL_CMD_EMPTY": "E_FAIL_DETAIL_CMD_EMPTY",
    "DETAIL_INDEX_MISMATCH": "E_DETAIL_INDEX_MISMATCH",
    "FAIL_LOGS_MISSING": "E_FAIL_LOGS_MISSING",
    "FAIL_LOGS_DUPLICATE": "E_FAIL_LOGS_DUPLICATE",
    "FAIL_LOGS_NOT_IN_FAILED_STEPS": "E_FAIL_LOGS_NOT_IN_FAILED_STEPS",
    "FAIL_LOG_PATH_MISSING": "E_FAIL_LOG_PATH_MISSING",
    "FAIL_LOGS_MISSING_FOR_STEP": "E_FAIL_LOGS_MISSING_FOR_STEP",
}


SUMMARY_REPORT_CODES = {
    "SUMMARY_MISSING": "E_SUMMARY_MISSING",
    "SUMMARY_EMPTY": "E_SUMMARY_EMPTY",
    "SUMMARY_STATUS_MISSING": "E_SUMMARY_STATUS_MISSING",
    "REQUIRE_PASS": "E_REQUIRE_PASS",
    "INDEX_INVALID": "E_INDEX_INVALID",
    "PASS_KEY_MISSING": "E_PASS_KEY_MISSING",
    "REPORT_INDEX_MISMATCH": "E_REPORT_INDEX_MISMATCH",
    "INDEX_REPORTS_MISSING": "E_INDEX_REPORTS_MISSING",
    "INDEX_PATH_MISSING": "E_INDEX_PATH_MISSING",
    "SUMMARY_INDEX_PATH_MISMATCH": "E_SUMMARY_INDEX_PATH_MISMATCH",
    "BRIEF_HINT_EMPTY": "E_BRIEF_HINT_EMPTY",
    "BRIEF_EXISTS_INVALID": "E_BRIEF_EXISTS_INVALID",
    "BRIEF_EXISTS_MISMATCH": "E_BRIEF_EXISTS_MISMATCH",
    "PASS_BRIEF_REQUIRED": "E_PASS_BRIEF_REQUIRED",
    "TRIAGE_HINT_EMPTY": "E_TRIAGE_HINT_EMPTY",
    "TRIAGE_EXISTS_INVALID": "E_TRIAGE_EXISTS_INVALID",
    "TRIAGE_EXISTS_MISMATCH": "E_TRIAGE_EXISTS_MISMATCH",
    "PASS_TRIAGE_REQUIRED": "E_PASS_TRIAGE_REQUIRED",
}
