#!/usr/bin/env python
from __future__ import annotations

from pathlib import Path


PROFILE_AND_PIPELINE_TOKENS = [
    "--profile",
    '"full", "core_lang", "seamgrim"',
    "SANITY_SUMMARY_STEP_FIELDS",
    "build_sanity_summary_fields(",
    '"ci_sanity_pipeline_emit_flags_ok"',
    '"ci_sanity_pipeline_emit_flags_selftest_ok"',
    '"ci_sanity_emit_artifacts_sanity_contract_selftest_ok"',
    '"ci_sanity_age2_completion_gate_selftest_ok"',
    '"ci_sanity_age2_close_ok"',
    '"ci_sanity_age2_close_selftest_ok"',
    '"ci_sanity_age3_completion_gate_selftest_ok"',
    '"ci_sanity_age3_close_ok"',
    '"ci_sanity_age3_close_selftest_ok"',
    '"ci_sanity_age3_bogae_geoul_visibility_smoke_ok"',
    '"ci_sanity_age3_bogae_geoul_visibility_smoke_report_path"',
    '"ci_sanity_age3_bogae_geoul_visibility_smoke_report_exists"',
    '"ci_sanity_age3_bogae_geoul_visibility_smoke_schema"',
    '"ci_sanity_age3_bogae_geoul_visibility_smoke_overall_ok"',
    '"ci_sanity_age3_bogae_geoul_visibility_smoke_checks_ok"',
    '"ci_sanity_age3_bogae_geoul_visibility_smoke_sim_state_hash_changes"',
    '"ci_sanity_age3_bogae_geoul_visibility_smoke_sim_bogae_hash_changes"',
    '"ci_sanity_age2_completion_gate_failure_codes"',
    '"ci_sanity_age2_completion_gate_failure_code_count"',
    '"ci_sanity_age3_completion_gate_failure_codes"',
    '"ci_sanity_age3_completion_gate_failure_code_count"',
    "build_completion_gate_failure_code_summary_fields(",
    '"ci_sanity_age5_combined_heavy_policy_selftest_ok"',
    '"ci_sanity_profile_matrix_full_real_smoke_policy_selftest_ok"',
    '"ci_sanity_dynamic_source_profile_split_selftest_ok"',
    '"ci_sanity_age5_combined_heavy_report_schema"',
    '"ci_sanity_age5_combined_heavy_required_reports"',
    '"ci_sanity_age5_combined_heavy_required_criteria"',
    '"ci_sanity_age5_combined_heavy_child_summary_default_fields"',
    '"ci_sanity_age5_combined_heavy_combined_contract_summary_fields"',
    '"ci_sanity_age5_combined_heavy_full_summary_contract_fields"',
    '"pending"',
    '"na"',
    "pipeline_emit_flags_check",
    "tests/run_ci_pipeline_emit_flags_check.py",
    "pipeline_emit_flags_selftest",
    "tests/run_ci_pipeline_emit_flags_check_selftest.py",
    "E_CI_SANITY_PIPELINE_FLAGS_SELFTEST_FAIL",
    "ci_emit_artifacts_sanity_contract_selftest",
    "tests/run_ci_emit_artifacts_sanity_contract_check_selftest.py",
    "E_CI_SANITY_EMIT_ARTIFACTS_SANITY_CONTRACT_SELFTEST_FAIL",
    "age5_combined_heavy_policy_selftest",
    "tests/run_age5_combined_heavy_policy_selftest.py",
    "E_CI_SANITY_AGE5_COMBINED_HEAVY_POLICY_SELFTEST_FAIL",
    "profile_matrix_full_real_smoke_policy_selftest",
    "tests/run_profile_matrix_full_real_smoke_policy_selftest.py",
    "E_CI_SANITY_PROFILE_MATRIX_FULL_REAL_SMOKE_POLICY_SELFTEST_FAIL",
    "profile_matrix_full_real_smoke_check_selftest",
    "tests/run_ci_profile_matrix_full_real_smoke_check_selftest.py",
    "E_CI_SANITY_PROFILE_MATRIX_FULL_REAL_SMOKE_CHECK_SELFTEST_FAIL",
    "fixed64_darwin_probe_schedule_policy_check",
    "tests/run_fixed64_darwin_probe_schedule_policy_check.py",
    "E_CI_SANITY_FIXED64_DARWIN_PROBE_SCHEDULE_POLICY_CHECK_FAIL",
    "fixed64_darwin_real_report_contract_check",
    "tests/run_fixed64_darwin_real_report_contract_check.py",
    "fixed64_cross_platform_probe_darwin.detjson",
    "fixed64_threeway_inputs.contract.detjson",
    "--resolve-threeway-inputs",
    "--resolve-inputs-json-out",
    "fixed64_threeway_inputs.contract.detjson",
    "--resolve-inputs-strict-invalid",
    "--resolve-inputs-require-when-env",
    "DDN_ENABLE_DARWIN_PROBE",
    "--resolve-input-candidate",
    "fixed64_darwin_probe_artifact.detjson",
    "E_CI_SANITY_FIXED64_DARWIN_REAL_REPORT_CONTRACT_CHECK_FAIL",
    "fixed64_darwin_real_report_live_check",
    "tests/run_fixed64_darwin_real_report_live_check.py",
    "--allow-pass-contract-only",
    "completion_gate_reports[\"fixed64_live_report\"]",
    "ci_sanity_fixed64_live_summary_fields_selftest",
    "tests/run_ci_sanity_fixed64_live_summary_fields_selftest.py",
    "E_CI_SANITY_FIXED64_LIVE_SUMMARY_FIELDS_SELFTEST_FAIL",
    "fixed64_darwin_real_report_live_check_selftest",
    "tests/run_fixed64_darwin_real_report_live_check_selftest.py",
    "E_CI_SANITY_FIXED64_DARWIN_REAL_REPORT_LIVE_SELFTEST_FAIL",
    "E_CI_SANITY_FIXED64_DARWIN_REAL_REPORT_LIVE_CHECK_FAIL",
    "fixed64_darwin_real_report_readiness_check_selftest",
    "tests/run_fixed64_darwin_real_report_readiness_check_selftest.py",
    "E_CI_SANITY_FIXED64_DARWIN_REAL_REPORT_READINESS_SELFTEST_FAIL",
    "fixed64_threeway_inputs_selftest",
    "tests/run_fixed64_threeway_inputs_selftest.py",
    "E_CI_SANITY_FIXED64_THREEWAY_INPUTS_SELFTEST_FAIL",
    "fixed64_cross_platform_threeway_gate_selftest",
    "tests/run_fixed64_cross_platform_threeway_gate_selftest.py",
    "E_CI_SANITY_FIXED64_THREEWAY_GATE_SELFTEST_FAIL",
    "\"ci_sanity_fixed64_live_summary_fields_selftest_ok\"",
    "\"ci_sanity_fixed64_darwin_real_report_live_check_selftest_ok\"",
    "\"ci_sanity_fixed64_threeway_inputs_selftest_ok\"",
    "\"ci_sanity_fixed64_darwin_real_report_live_report_path\"",
    "\"ci_sanity_fixed64_darwin_real_report_live_report_exists\"",
    "\"ci_sanity_fixed64_darwin_real_report_live_status\"",
    "\"ci_sanity_fixed64_darwin_real_report_live_resolved_status\"",
    "\"ci_sanity_fixed64_darwin_real_report_live_resolved_source\"",
    "\"ci_sanity_fixed64_darwin_real_report_live_resolve_invalid_hit_count\"",
    "\"ci_sanity_fixed64_darwin_real_report_live_resolved_source_zip\"",
    "build_fixed64_darwin_real_report_live_summary_fields(",
    "ci_profile_split_contract_check",
    "tests/run_ci_profile_split_contract_check.py",
    "E_CI_SANITY_PROFILE_SPLIT_CONTRACT_FAIL",
    "ci_sanity_dynamic_source_profile_split_selftest",
    "tests/run_ci_sanity_dynamic_source_profile_split_selftest.py",
    "E_CI_SANITY_DYNAMIC_SOURCE_PROFILE_SPLIT_SELFTEST_FAIL",
    "ci_profile_matrix_lightweight_contract_selftest",
    "tests/run_ci_profile_matrix_lightweight_contract_selftest.py",
    "E_CI_SANITY_PROFILE_MATRIX_LIGHTWEIGHT_CONTRACT_SELFTEST_FAIL",
    "ci_profile_matrix_snapshot_helper_selftest",
    "tests/run_ci_profile_matrix_snapshot_helper_selftest.py",
    "E_CI_SANITY_PROFILE_MATRIX_SNAPSHOT_HELPER_SELFTEST_FAIL",
    "resolve_completion_gate_report_dir(",
    "build_completion_gate_report_paths(",
    "completion_gate_reports = build_completion_gate_report_paths(args.profile)",
    "age2_completion_gate.{profile}.dynamic.last.detjson",
    "age3_completion_gate.{profile}.dynamic.last.detjson",
    "age4_proof_transport_contract_selftest.{profile}.dynamic.last.detjson",
    "pack_golden_age5_surface_selftest.{profile}.dynamic.last.detjson",
    "DDN_AGE2_DYNAMIC_SHARD_SOURCE_REPORT",
    "DDN_AGE3_DYNAMIC_SHARD_SOURCE_REPORT",
    "DDN_AGE4_PROOF_TRANSPORT_DYNAMIC_WORKER_SOURCE_REPORT",
    "DDN_AGE5_SURFACE_DYNAMIC_GROUP_SOURCE_REPORT",
    "age2_completion_gate_selftest",
    "tests/run_age2_completion_gate_selftest.py",
    "E_CI_SANITY_AGE2_COMPLETION_GATE_SELFTEST_FAIL",
    "age2_close_selftest",
    "tests/run_age2_close_selftest.py",
    "E_CI_SANITY_AGE2_CLOSE_SELFTEST_FAIL",
    "age2_close",
    "tests/run_age2_close.py",
    "E_CI_SANITY_AGE2_CLOSE_FAIL",
    "age3_completion_gate_selftest",
    "tests/run_age3_completion_gate_selftest.py",
    "E_CI_SANITY_AGE3_COMPLETION_GATE_SELFTEST_FAIL",
    "age3_close_selftest",
    "tests/run_age3_close_selftest.py",
    "E_CI_SANITY_AGE3_CLOSE_SELFTEST_FAIL",
    "age3_close",
    "tests/run_age3_close.py",
    "E_CI_SANITY_AGE3_CLOSE_FAIL",
    "--must-report-out",
    "--should-report-out",
    "--pack-report-out",
    "--run-seamgrim",
    "--seamgrim-report",
    "--ui-age3-report",
    "age2_completion_must_pack_report.",
    "age2_completion_should_pack_report.",
    "age2_close_report.",
    "age3_completion_pack_report.",
    "age3_close_report.",
    "seamgrim_ci_gate_report.",
    "seamgrim_ui_age3_gate_report.",
]

CONTRACT_AND_REGISTRY_TOKENS = [
    "contract_tier_unsupported_check",
    "tests/run_contract_tier_unsupported_check.py",
    "E_CI_SANITY_CONTRACT_TIER_UNSUPPORTED_CHECK_FAIL",
    "contract_tier_age3_min_enforcement_check",
    "tests/run_contract_tier_age3_min_enforcement_check.py",
    "E_CI_SANITY_CONTRACT_TIER_AGE3_MIN_ENFORCEMENT_CHECK_FAIL",
    "map_access_contract_check",
    "tests/run_map_access_contract_check.py",
    "E_CI_SANITY_MAP_ACCESS_CONTRACT_CHECK_FAIL",
    "gaji_registry_strict_audit_check",
    "tests/run_gaji_registry_strict_audit_check.py",
    "E_CI_SANITY_GAJI_REGISTRY_STRICT_AUDIT_CHECK_FAIL",
    "gaji_registry_defaults_check",
    "tests/run_gaji_registry_defaults_check.py",
    "E_CI_SANITY_GAJI_REGISTRY_DEFAULTS_CHECK_FAIL",
    "stdlib_catalog_check",
    "tests/run_stdlib_catalog_check.py",
    "E_CI_SANITY_STDLIB_CATALOG_CHECK_FAIL",
    "stdlib_catalog_check_selftest",
    "tests/run_stdlib_catalog_check_selftest.py",
    "E_CI_SANITY_STDLIB_CATALOG_CHECK_SELFTEST_FAIL",
    "tensor_v0_pack_check",
    "tests/run_tensor_v0_pack_check.py",
    "E_CI_SANITY_TENSOR_V0_PACK_CHECK_FAIL",
    "tensor_v0_cli_check",
    "tests/run_tensor_v0_cli_check.py",
    "E_CI_SANITY_TENSOR_V0_CLI_CHECK_FAIL",
]

SEAMGRIM_CONTRACT_TOKENS = [
    "seamgrim_ci_gate_sam_seulgi_family_step_check",
    "tests/run_seamgrim_ci_gate_sam_seulgi_family_step_check.py",
    "E_CI_SANITY_SAM_SEULGI_FAMILY_STEP_FAIL",
    "seamgrim_ci_gate_seed_meta_step_check",
    "tests/run_seamgrim_ci_gate_seed_meta_step_check.py",
    "E_CI_SANITY_SEED_META_STEP_FAIL",
    "seamgrim_ci_gate_runtime5_passthrough_check",
    "tests/run_seamgrim_ci_gate_runtime5_passthrough_check.py",
    "E_CI_SANITY_RUNTIME5_PASSTHROUGH_FAIL",
    "seamgrim_ci_gate_lesson_warning_step_check",
    "tests/run_seamgrim_ci_gate_lesson_warning_step_check.py",
    "E_CI_SANITY_LESSON_WARNING_STEP_FAIL",
    "seamgrim_ci_gate_stateful_preview_step_check",
    "tests/run_seamgrim_ci_gate_stateful_preview_step_check.py",
    "E_CI_SANITY_STATEFUL_PREVIEW_STEP_FAIL",
    "seamgrim_ci_gate_wasm_web_smoke_step_check",
    "tests/run_seamgrim_ci_gate_wasm_web_smoke_step_check.py",
    "E_CI_SANITY_WASM_WEB_SMOKE_STEP_FAIL",
    "seamgrim_ci_gate_wasm_web_smoke_step_check_selftest",
    "tests/run_seamgrim_ci_gate_wasm_web_smoke_step_check_selftest.py",
    "E_CI_SANITY_WASM_WEB_SMOKE_STEP_SELFTEST_FAIL",
    "seamgrim_ci_gate_pack_evidence_tier_step_check",
    "tests/run_seamgrim_ci_gate_pack_evidence_tier_step_check.py",
    "E_CI_SANITY_PACK_EVIDENCE_TIER_STEP_FAIL",
    "seamgrim_ci_gate_pack_evidence_tier_step_check_selftest",
    "tests/run_seamgrim_ci_gate_pack_evidence_tier_step_check_selftest.py",
    "E_CI_SANITY_PACK_EVIDENCE_TIER_STEP_SELFTEST_FAIL",
    "seamgrim_ci_gate_pack_evidence_tier_runner_check",
    "tests/run_pack_evidence_tier_check.py",
    "E_CI_SANITY_PACK_EVIDENCE_TIER_RUNNER_CHECK_FAIL",
    "seamgrim_ci_gate_pack_evidence_tier_report_check",
    "tests/run_pack_evidence_tier_report_check.py",
    "E_CI_SANITY_PACK_EVIDENCE_TIER_REPORT_CHECK_FAIL",
    "seamgrim_ci_gate_pack_evidence_tier_report_check_selftest",
    "tests/run_pack_evidence_tier_report_check_selftest.py",
    "E_CI_SANITY_PACK_EVIDENCE_TIER_REPORT_CHECK_SELFTEST_FAIL",
    "seamgrim_interface_boundary_contract_check",
    "tests/run_seamgrim_interface_boundary_contract_check.py",
    "E_CI_SANITY_SEAMGRIM_INTERFACE_BOUNDARY_FAIL",
    "seamgrim_overlay_session_wired_consistency_check",
    "tests/run_seamgrim_overlay_session_wired_consistency_check.py",
    "E_CI_SANITY_OVERLAY_SESSION_WIRED_CONSISTENCY_FAIL",
    "seamgrim_overlay_session_diag_parity_check",
    "tests/run_seamgrim_overlay_session_diag_parity_check.py",
    "E_CI_SANITY_OVERLAY_SESSION_DIAG_PARITY_FAIL",
    "seamgrim_overlay_compare_diag_parity_check",
    "tests/run_seamgrim_overlay_compare_diag_parity_check.py",
    "E_CI_SANITY_OVERLAY_COMPARE_DIAG_PARITY_FAIL",
    "seamgrim_wasm_cli_diag_parity_check",
    "tests/run_seamgrim_wasm_cli_diag_parity_check.py",
    "E_CI_SANITY_WASM_CLI_DIAG_PARITY_FAIL",
]

PACK_SELFTEST_TOKENS = [
    "age5_close_pack_contract_selftest",
    "tests/run_age5_close_pack_contract_selftest.py",
    "E_CI_SANITY_AGE5_CLOSE_PACK_CONTRACT_SELFTEST_FAIL",
    "ci_pack_golden_age5_surface_selftest",
    "tests/run_pack_golden_age5_surface_selftest.py",
    "E_CI_SANITY_PACK_GOLDEN_AGE5_SURFACE_SELFTEST_FAIL",
    "ci_pack_golden_guideblock_selftest",
    "tests/run_pack_golden_guideblock_selftest.py",
    "E_CI_SANITY_PACK_GOLDEN_GUIDEBLOCK_SELFTEST_FAIL",
    "ci_pack_golden_exec_policy_selftest",
    "tests/run_pack_golden_exec_policy_selftest.py",
    "E_CI_SANITY_PACK_GOLDEN_EXEC_POLICY_SELFTEST_FAIL",
    "ci_pack_golden_jjaim_flatten_selftest",
    "tests/run_pack_golden_jjaim_flatten_selftest.py",
    "E_CI_SANITY_PACK_GOLDEN_JJAIM_FLATTEN_SELFTEST_FAIL",
    "ci_pack_golden_event_model_selftest",
    "tests/run_pack_golden_event_model_selftest.py",
    "E_CI_SANITY_PACK_GOLDEN_EVENT_MODEL_SELFTEST_FAIL",
    "ci_pack_golden_lang_consistency_selftest",
    "tests/run_pack_golden_lang_consistency_selftest.py",
    "E_CI_SANITY_PACK_GOLDEN_LANG_CONSISTENCY_SELFTEST_FAIL",
    "ci_pack_golden_metadata_selftest",
    "tests/run_pack_golden_metadata_selftest.py",
    "E_CI_SANITY_PACK_GOLDEN_METADATA_SELFTEST_FAIL",
    "ci_pack_golden_graph_export_selftest",
    "tests/run_pack_golden_graph_export_selftest.py",
    "E_CI_SANITY_PACK_GOLDEN_GRAPH_EXPORT_SELFTEST_FAIL",
    "ci_canon_ast_dpack_selftest",
    "tests/run_canon_ast_dpack_selftest.py",
    "E_CI_SANITY_CANON_AST_DPACK_SELFTEST_FAIL",
]

GOGAE9_PACK_TOKENS = [
    "w92_aot_pack_check",
    "tests/run_w92_aot_pack_check.py",
    "E_CI_SANITY_W92_AOT_PACK_CHECK_FAIL",
    "w93_universe_pack_check",
    "tests/run_w93_universe_pack_check.py",
    "E_CI_SANITY_W93_UNIVERSE_PACK_CHECK_FAIL",
    "w94_social_pack_check",
    "tests/run_w94_social_pack_check.py",
    "E_CI_SANITY_W94_SOCIAL_PACK_CHECK_FAIL",
    "w95_cert_pack_check",
    "tests/run_w95_cert_pack_check.py",
    "E_CI_SANITY_W95_CERT_PACK_CHECK_FAIL",
    "w96_somssi_pack_check",
    "tests/run_w96_somssi_pack_check.py",
    "E_CI_SANITY_W96_SOMSSI_PACK_CHECK_FAIL",
    "w97_self_heal_pack_check",
    "tests/run_w97_self_heal_pack_check.py",
    "E_CI_SANITY_W97_SELF_HEAL_PACK_CHECK_FAIL",
]

AGE3_CRITERIA_CONTRACT_TOKENS = [
    "from _ci_age3_completion_gate_contract import (",
    "AGE3_COMPLETION_GATE_CRITERIA_NAMES,",
    "age3_completion_gate_criteria_summary_key,",
    "def _extract_age3_criteria_status_map(",
    "def build_age3_completion_gate_criteria_summary_fields(",
    "criteria_status_map = _extract_age3_criteria_status_map(load_json_snapshot(report_path))",
    "for criteria_name in AGE3_COMPLETION_GATE_CRITERIA_NAMES:",
    "age3_completion_gate_criteria_summary_key(criteria_name)",
]

REQUIRED_TOKENS = [
    *PROFILE_AND_PIPELINE_TOKENS,
    *CONTRACT_AND_REGISTRY_TOKENS,
    *SEAMGRIM_CONTRACT_TOKENS,
    *PACK_SELFTEST_TOKENS,
    *GOGAE9_PACK_TOKENS,
    *AGE3_CRITERIA_CONTRACT_TOKENS,
]


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    target = root / "tests" / "run_ci_sanity_gate.py"
    if not target.exists():
        print(f"missing target: {target}")
        return 1
    text = target.read_text(encoding="utf-8")

    missing = [token for token in REQUIRED_TOKENS if token not in text]
    if missing:
        print("ci sanity gate diagnostics check failed:")
        for token in missing[:12]:
            print(f" - missing token: {token}")
        return 1

    print("ci sanity gate diagnostics check ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
