#!/usr/bin/env python
from __future__ import annotations

from pathlib import Path

from _ci_fail_and_exit_contract import validate_fail_and_exit_block_contract


COMMON_SANITY_STEP_GATE_TOKENS = (
    "ci_pack_golden_age5_surface_selftest",
    "ci_pack_golden_guideblock_selftest",
    "ci_pack_golden_exec_policy_selftest",
    "ci_pack_golden_jjaim_flatten_selftest",
    "ci_pack_golden_event_model_selftest",
    "ci_pack_golden_lang_consistency_selftest",
    "ci_pack_golden_metadata_selftest",
    "ci_pack_golden_graph_export_selftest",
    "ci_canon_ast_dpack_selftest",
    "ci_profile_split_contract_check",
    "contract_tier_unsupported_check",
    "contract_tier_age3_min_enforcement_check",
    "map_access_contract_check",
    "gaji_registry_strict_audit_check",
    "gaji_registry_defaults_check",
    "stdlib_catalog_check",
    "stdlib_catalog_check_selftest",
    "tensor_v0_pack_check",
    "tensor_v0_cli_check",
    "age5_combined_heavy_policy_selftest",
    "profile_matrix_full_real_smoke_policy_selftest",
    "profile_matrix_full_real_smoke_check_selftest",
    "age2_completion_gate",
    "age2_completion_gate_selftest",
    "age3_completion_gate",
    "age3_completion_gate_selftest",
    "fixed64_darwin_real_report_contract_check",
    "fixed64_darwin_real_report_live_check",
    "fixed64_darwin_real_report_readiness_check_selftest",
    "ci_profile_matrix_lightweight_contract_selftest",
    "ci_profile_matrix_snapshot_helper_selftest",
    "w92_aot_pack_check",
    "w93_universe_pack_check",
    "w94_social_pack_check",
    "w95_cert_pack_check",
    "w96_somssi_pack_check",
    "w97_self_heal_pack_check",
    "seamgrim_interface_boundary_contract_check",
    "seamgrim_wasm_cli_diag_parity_check",
)

COMMON_SANITY_STEP_CHECK_PATH_TOKENS = (
    "tests/run_pack_golden_age5_surface_selftest.py",
    "tests/run_pack_golden_guideblock_selftest.py",
    "tests/run_pack_golden_exec_policy_selftest.py",
    "tests/run_pack_golden_jjaim_flatten_selftest.py",
    "tests/run_pack_golden_event_model_selftest.py",
    "tests/run_pack_golden_lang_consistency_selftest.py",
    "tests/run_pack_golden_metadata_selftest.py",
    "tests/run_pack_golden_graph_export_selftest.py",
    "tests/run_canon_ast_dpack_selftest.py",
    "tests/run_ci_profile_split_contract_check.py",
    "tests/run_contract_tier_unsupported_check.py",
    "tests/run_contract_tier_age3_min_enforcement_check.py",
    "tests/run_map_access_contract_check.py",
    "tests/run_gaji_registry_strict_audit_check.py",
    "tests/run_gaji_registry_defaults_check.py",
    "tests/run_stdlib_catalog_check.py",
    "tests/run_stdlib_catalog_check_selftest.py",
    "tests/run_tensor_v0_pack_check.py",
    "tests/run_tensor_v0_cli_check.py",
    "tests/run_age5_combined_heavy_policy_selftest.py",
    "tests/run_profile_matrix_full_real_smoke_policy_selftest.py",
    "tests/run_ci_profile_matrix_full_real_smoke_check_selftest.py",
    "tests/run_age2_completion_gate.py",
    "tests/run_age2_completion_gate_selftest.py",
    "tests/run_age3_completion_gate.py",
    "tests/run_age3_completion_gate_selftest.py",
    "tests/run_fixed64_darwin_real_report_contract_check.py",
    "tests/run_fixed64_darwin_real_report_live_check.py",
    "tests/run_fixed64_darwin_real_report_readiness_check_selftest.py",
    "tests/run_ci_profile_matrix_lightweight_contract_selftest.py",
    "tests/run_ci_profile_matrix_snapshot_helper_selftest.py",
    "tests/run_w92_aot_pack_check.py",
    "tests/run_w93_universe_pack_check.py",
    "tests/run_w94_social_pack_check.py",
    "tests/run_w95_cert_pack_check.py",
    "tests/run_w96_somssi_pack_check.py",
    "tests/run_w97_self_heal_pack_check.py",
    "tests/run_seamgrim_interface_boundary_contract_check.py",
    "tests/run_seamgrim_wasm_cli_diag_parity_check.py",
)

PROFILE_MATRIX_SUMMARY_TOKENS = (
    "ci_profile_matrix_gate_selftest_status",
    "ci_profile_matrix_gate_selftest_total_elapsed_ms",
    "ci_profile_matrix_gate_selftest_selected_real_profiles",
    "ci_profile_matrix_gate_selftest_core_lang_elapsed_ms",
    "ci_profile_matrix_gate_selftest_full_elapsed_ms",
    "ci_profile_matrix_gate_selftest_seamgrim_elapsed_ms",
    "ci_profile_matrix_gate_selftest_aggregate_summary_sanity_ok",
    "ci_profile_matrix_gate_selftest_aggregate_summary_checked_profiles",
    "ci_profile_matrix_gate_selftest_aggregate_summary_failed_profiles",
    "ci_profile_matrix_gate_selftest_aggregate_summary_skipped_profiles",
    "ci_profile_matrix_gate_selftest_core_lang_aggregate_summary_status",
    "ci_profile_matrix_gate_selftest_core_lang_aggregate_summary_ok",
    "ci_profile_matrix_gate_selftest_core_lang_aggregate_summary_values",
    "ci_profile_matrix_gate_selftest_full_aggregate_summary_status",
    "ci_profile_matrix_gate_selftest_full_aggregate_summary_ok",
    "ci_profile_matrix_gate_selftest_full_aggregate_summary_values",
    "ci_profile_matrix_gate_selftest_seamgrim_aggregate_summary_status",
    "ci_profile_matrix_gate_selftest_seamgrim_aggregate_summary_ok",
    "ci_profile_matrix_gate_selftest_seamgrim_aggregate_summary_values",
)

CI_SANITY_SUMMARY_TOKENS = (
    "ci_sanity_gate_status",
    "ci_sanity_gate_code",
    "ci_sanity_gate_profile",
    "ci_sanity_pipeline_emit_flags_ok",
    "ci_sanity_pipeline_emit_flags_selftest_ok",
    "ci_sanity_age2_completion_gate_ok",
    "ci_sanity_age2_completion_gate_selftest_ok",
    "ci_sanity_age2_completion_gate_failure_codes",
    "ci_sanity_age2_completion_gate_failure_code_count",
    "ci_sanity_age3_completion_gate_ok",
    "ci_sanity_age3_completion_gate_selftest_ok",
    "ci_sanity_age3_completion_gate_failure_codes",
    "ci_sanity_age3_completion_gate_failure_code_count",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_ok",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_report_path",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_report_exists",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_schema",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_overall_ok",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_checks_ok",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_sim_state_hash_changes",
    "ci_sanity_age3_bogae_geoul_visibility_smoke_sim_bogae_hash_changes",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_ok",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_report_path",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_report_exists",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_schema",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_docs_issue_count",
    "ci_sanity_seamgrim_pack_evidence_tier_runner_repo_issue_count",
    "ci_sanity_age5_combined_heavy_policy_selftest_ok",
    "ci_sanity_age5_combined_heavy_report_schema",
    "ci_sanity_age5_combined_heavy_required_reports",
    "ci_sanity_age5_combined_heavy_required_criteria",
    "ci_sanity_age5_combined_heavy_child_summary_default_fields",
    "ci_sanity_age5_combined_heavy_combined_contract_summary_fields",
    "ci_sanity_age5_combined_heavy_full_summary_contract_fields",
    "ci_sanity_profile_matrix_full_real_smoke_policy_selftest_ok",
    "ci_sanity_seamgrim_interface_boundary_ok",
    "ci_sanity_overlay_session_wired_consistency_ok",
    "ci_sanity_overlay_session_diag_parity_ok",
    "ci_sanity_overlay_compare_diag_parity_ok",
    "ci_sanity_pack_golden_lang_consistency_ok",
    "ci_sanity_pack_golden_metadata_ok",
    "ci_sanity_pack_golden_graph_export_ok",
    "ci_sanity_canon_ast_dpack_ok",
    "ci_sanity_contract_tier_unsupported_ok",
    "ci_sanity_contract_tier_age3_min_enforcement_ok",
    "ci_sanity_map_access_contract_ok",
    "ci_sanity_stdlib_catalog_ok",
    "ci_sanity_stdlib_catalog_selftest_ok",
    "ci_sanity_tensor_v0_pack_ok",
    "ci_sanity_tensor_v0_cli_ok",
    "ci_sanity_fixed64_darwin_real_report_contract_ok",
    "ci_sanity_fixed64_darwin_real_report_live_ok",
    "ci_sanity_fixed64_darwin_real_report_readiness_selftest_ok",
    "ci_sanity_fixed64_darwin_real_report_live_report_path",
    "ci_sanity_fixed64_darwin_real_report_live_report_exists",
    "ci_sanity_fixed64_darwin_real_report_live_status",
    "ci_sanity_fixed64_darwin_real_report_live_resolved_status",
    "ci_sanity_fixed64_darwin_real_report_live_resolved_source",
    "ci_sanity_fixed64_darwin_real_report_live_resolve_invalid_hit_count",
    "ci_sanity_fixed64_darwin_real_report_live_resolved_source_zip",
    "ci_sanity_registry_strict_audit_ok",
    "ci_sanity_registry_defaults_ok",
)

CI_SYNC_SUMMARY_TOKENS = (
    "ci_sync_readiness_status",
    "ci_sync_readiness_code",
    "ci_sync_readiness_sanity_profile",
    "ci_sync_readiness_ci_sanity_pipeline_emit_flags_ok",
    "ci_sync_readiness_ci_sanity_pipeline_emit_flags_selftest_ok",
    "ci_sync_readiness_ci_sanity_age2_completion_gate_ok",
    "ci_sync_readiness_ci_sanity_age2_completion_gate_selftest_ok",
    "ci_sync_readiness_ci_sanity_age2_completion_gate_failure_codes",
    "ci_sync_readiness_ci_sanity_age2_completion_gate_failure_code_count",
    "ci_sync_readiness_ci_sanity_age3_completion_gate_ok",
    "ci_sync_readiness_ci_sanity_age3_completion_gate_selftest_ok",
    "ci_sync_readiness_ci_sanity_age3_completion_gate_failure_codes",
    "ci_sync_readiness_ci_sanity_age3_completion_gate_failure_code_count",
    "ci_sync_readiness_ci_sanity_pack_golden_graph_export_ok",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_ok",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_report_path",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_report_exists",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_schema",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_overall_ok",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_checks_ok",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_sim_state_hash_changes",
    "ci_sync_readiness_ci_sanity_age3_bogae_geoul_visibility_smoke_sim_bogae_hash_changes",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_ok",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_report_path",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_report_exists",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_schema",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_docs_issue_count",
    "ci_sync_readiness_ci_sanity_seamgrim_pack_evidence_tier_runner_repo_issue_count",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_report_path",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_report_exists",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_status",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_status",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_source",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolve_invalid_hit_count",
    "ci_sync_readiness_ci_sanity_fixed64_darwin_real_report_live_resolved_source_zip",
    "ci_sync_readiness_ci_sanity_age5_combined_heavy_policy_selftest_ok",
    "ci_sync_readiness_ci_sanity_age5_combined_heavy_report_schema",
    "ci_sync_readiness_ci_sanity_age5_combined_heavy_required_reports",
    "ci_sync_readiness_ci_sanity_age5_combined_heavy_required_criteria",
    "ci_sync_readiness_ci_sanity_age5_combined_heavy_child_summary_default_fields",
    "ci_sync_readiness_ci_sanity_age5_combined_heavy_combined_contract_summary_fields",
    "ci_sync_readiness_ci_sanity_age5_combined_heavy_full_summary_contract_fields",
    "ci_sync_readiness_ci_sanity_profile_matrix_full_real_smoke_policy_selftest_ok",
)

FIXED64_SUMMARY_TOKENS = (
    "fixed64_threeway_status",
    "fixed64_threeway_ok",
)

AGE3_CRITERIA_CONTRACT_TOKENS = (
    "from _ci_age3_completion_gate_contract import (",
    "AGE3_COMPLETION_GATE_CRITERIA_NAMES,",
    "age3_completion_gate_criteria_summary_key,",
    "age3_completion_gate_criteria_sync_summary_key,",
    "SANITY_SUMMARY_TOKEN_CONTRACT.extend(",
    "SYNC_SUMMARY_TOKEN_CONTRACT.extend(",
)

SEAMGRIM_FOCUS_STEP_TOKEN_TUPLES = (
    '("seamgrim_lesson_warning_tokens", "lesson_warning_tokens")',
    '("seamgrim_stateful_sim_preview_upgrade", "stateful_sim_preview_upgrade")',
)

REQUIRED_TOKEN_MAP = {
    "tests/run_ci_aggregate_gate.py": [
        "ci_sanity_gate_base_name",
        "ci_sanity_gate_report",
        "check_ci_sanity_gate",
        "tests/run_ci_sanity_gate.py",
        "check_ci_sanity_gate_diagnostics",
        "tests/run_ci_sanity_gate_diagnostics_check.py",
        "check_ci_emit_artifacts_sanity_contract",
        "tests/run_ci_emit_artifacts_sanity_contract_check.py",
        "ci_emit_artifacts_sanity_contract_check",
        "check_ci_emit_artifacts_sanity_contract_selftest",
        "tests/run_ci_emit_artifacts_sanity_contract_check_selftest.py",
        "ci_emit_artifacts_sanity_contract_selftest",
        "def find_latest_failed_step_record() -> dict[str, object] | None:",
        "def print_fast_fail_step_detail(expected_rc: int) -> None:",
        "print_fast_fail_step_detail(exit_code)",
        "[ci-gate] fast-fail-step-detail name=",
        "[ci-gate] fast-fail-step-logs name=",
        "[ci-gate] fast-fail-step-rc-mismatch expected=",
        "check_ci_emit_artifacts_required_post_summary",
        "ci_emit_artifacts_required_post_summary_check",
        "allow-triage-exists-upgrade",
        "ci_profile_matrix_gate_selftest_base_name",
        "ci_profile_matrix_gate_selftest_report",
        '"ci_profile_matrix_gate_selftest": str(ci_profile_matrix_gate_selftest_report)',
        "--profile-matrix-selftest-real-profiles",
        "--profile-matrix-selftest-dry",
        "--profile-matrix-selftest-quick",
        "if args.profile_matrix_selftest_real_profiles.strip():",
        "--real-profiles",
        "args.profile_matrix_selftest_real_profiles.strip()",
        "if args.profile_matrix_selftest_dry:",
        'cmd.append("--dry-selftest")',
        "if args.profile_matrix_selftest_quick:",
        'cmd.append("--quick-selftest")',
        "append_ci_sanity_summary_lines(",
        "append_ci_profile_matrix_selftest_summary_lines(",
        "check_ci_aggregate_gate_sanity_diagnostics",
        "ci_aggregate_gate_sanity_diagnostics_check",
        "tests/run_ci_aggregate_gate_sanity_diagnostics_check.py",
        "check_ci_gate_report_index_selftest",
        "ci_gate_report_index_selftest",
        "tests/run_ci_gate_report_index_check_selftest.py",
        "check_ci_gate_report_index_diagnostics",
        "ci_gate_report_index_diagnostics_check",
        "tests/run_ci_gate_report_index_diagnostics_check.py",
        "check_ci_fail_and_exit_contract_selftest",
        "check_ci_fail_and_exit_contract_selftest_skipped",
        "ci_fail_and_exit_contract_selftest",
        "tests/run_ci_fail_and_exit_contract_selftest.py",
        "--skip-fail-and-exit-contract-selftest",
        "check_ci_gate_report_index_latest_smoke",
        "ci_gate_report_index_latest_smoke_check",
        "tests/run_ci_gate_report_index_latest_smoke_check.py",
        "check_ci_gate_report_index",
        "ci_gate_report_index_check",
        "tests/run_ci_gate_report_index_check.py",
        "report_index_required_steps_common",
        "report_index_required_steps_seamgrim",
        "resolve_report_index_required_steps",
        "report_index_required_steps",
        "require_step_contract",
        "--enforce-profile-step-contract",
        "--required-step",
        "check_ci_gate_report_index(require_step_contract=True)",
        "def find_step_record(name: str) -> dict[str, object] | None:",
        "def run_step_if_missing(name: str, runner) -> int:",
        'run_step_if_missing("ci_fail_and_exit_contract_selftest", check_ci_fail_and_exit_contract_selftest)',
        'run_step_if_missing("ci_gate_report_index_selftest", check_ci_gate_report_index_selftest)',
        'run_step_if_missing("ci_gate_report_index_diagnostics_check", check_ci_gate_report_index_diagnostics)',
        'run_step_if_missing("ci_emit_artifacts_baseline_check", check_ci_emit_artifacts_baseline)',
        "check_ci_pack_golden_event_model_selftest",
        "ci_pack_golden_event_model_selftest",
        "tests/run_pack_golden_event_model_selftest.py",
        "--json-out",
        "ci_profile_matrix_gate_selftest_report",
        "ci_pack_golden_event_model_selftest_ok=",
        "ci_sanity_contract_tier_unsupported_ok=",
        "ci_sanity_contract_tier_age3_min_enforcement_ok=",
        "ci_sanity_fixed64_darwin_real_report_live_ok=",
        "--lesson-warning-require-zero",
        "--lesson-warning-report-json-out",
        "check_seamgrim_ci_gate_lesson_warning_step",
        "seamgrim_ci_gate_lesson_warning_step_check",
        "tests/run_seamgrim_ci_gate_lesson_warning_step_check.py",
        "check_seamgrim_ci_gate_stateful_preview_step",
        "seamgrim_ci_gate_stateful_preview_step_check",
        "tests/run_seamgrim_ci_gate_stateful_preview_step_check.py",
        "check_seamgrim_ci_gate_wasm_web_smoke_step",
        "seamgrim_ci_gate_wasm_web_smoke_step_check",
        "tests/run_seamgrim_ci_gate_wasm_web_smoke_step_check.py",
        "check_seamgrim_ci_gate_wasm_web_smoke_step_selftest",
        "seamgrim_ci_gate_wasm_web_smoke_step_check_selftest",
        "tests/run_seamgrim_ci_gate_wasm_web_smoke_step_check_selftest.py",
        *AGE3_CRITERIA_CONTRACT_TOKENS,
    ],
    "tests/_ci_aggregate_diag_lib.py": [
        "def append_summary_lines(",
        "def append_prefixed_summary_lines(",
        "def build_snapshot(",
        "def build_typed_snapshot(",
        "from _ci_aggregate_diag_specs import (",
        "CI_SANITY_DEFAULT_SNAPSHOT",
        "PROFILE_MATRIX_DEFAULT_SNAPSHOT",
        "SEAMGRIM_FOCUS_STEP_SPECS",
        "load_ci_profile_matrix_selftest_snapshot",
        "ci_sanity_gate_report",
        "ci_sync_readiness_report",
        "fixed64_threeway_report",
        "from _ci_age3_completion_gate_contract import (",
        "age3_completion_gate_criteria_summary_key,",
        "age3_completion_gate_criteria_sync_summary_key,",
        "snapshot[f\"age3_completion_gate_criteria_{criteria_name}_ok\"]",
    ],
    "tests/_ci_fail_and_exit_contract.py": [
        "FAST_FAIL_REENTRY_GUARD_TOKENS",
        "FAIL_AND_EXIT_BLOCK_REQUIRED_TOKENS",
        "FAIL_AND_EXIT_BLOCK_FORBIDDEN_TOKENS",
        "def validate_fail_and_exit_block_contract(gate_text: str) -> list[str]:",
        "block_start = gate_text.find(\"def fail_and_exit(\")",
        "block_end = gate_text.find(\"if args.contract_only_aggregate:\")",
    ],
    "tests/_ci_aggregate_gate_mock_harness.py": [
        "def run_aggregate_gate_with_mock_failure(",
        "def build_step_map(index_doc: dict[str, object]) -> dict[str, dict[str, object]]:",
        "if name == observed_step_name:",
        "rc = int(fail_returncode) if name == fail_step_name else 0",
        "with redirect_stdout(stdout_buffer), redirect_stderr(stderr_buffer):",
    ],
    "tests/_ci_latest_smoke_contract.py": [
        "LATEST_SMOKE_SKIP_REASON_FAST_FAIL_PATH",
        "LATEST_SMOKE_SKIP_REASON_FLAG_DISABLED",
        "LATEST_SMOKE_SKIP_REASON_PENDING_FAILURE_SUMMARY_REGENERATION",
        "LATEST_SMOKE_SKIP_REASON_CI_GATE_RESULT_STATUS_NOT_PASS",
        "LATEST_SMOKE_SKIP_REASON_EXPECTED",
        "fast_fail_path",
        "flag_disabled",
        "pending_failure_summary_regeneration",
        "ci_gate_result_status_not_pass",
    ],
    "tests/run_ci_fail_and_exit_contract_selftest.py": [
        "validate_fail_and_exit_block_contract",
        "from _ci_aggregate_gate_mock_harness import build_step_map, run_aggregate_gate_with_mock_failure",
        "from _ci_latest_smoke_contract import (",
        "LATEST_SMOKE_SKIP_REASON_FAST_FAIL_PATH,",
        "LATEST_SMOKE_SKIP_REASON_FLAG_DISABLED,",
        "LATEST_SMOKE_SKIP_REASON_PENDING_FAILURE_SUMMARY_REGENERATION,",
        "LATEST_SMOKE_SKIP_REASON_CI_GATE_RESULT_STATUS_NOT_PASS,",
        "FAIL_AND_EXIT_BLOCK_REQUIRED_TOKENS",
        "FAIL_AND_EXIT_BLOCK_FORBIDDEN_TOKENS",
        "ci_latest_smoke_fast_fail_skip_case",
        "ci_latest_smoke_flag_disabled_case",
        "ci_latest_smoke_pending_regen_case",
        "ci_latest_smoke_not_pass_case",
        "ci_latest_smoke_execute_case",
        "ci_gate_report_index_latest_smoke_check: skipped reason=",
        "tests/run_ci_gate_report_index_latest_smoke_check.py",
        "missing required token in fail_and_exit:",
        "forbidden direct rerun token in fail_and_exit:",
        "fail_and_exit block boundary not found",
        "fail_and_exit contract selftest ok",
    ],
    "tests/_ci_aggregate_diag_specs.py": [
        "from _ci_aggregate_diag_specs_common import (",
        "from _ci_aggregate_diag_specs_profile_runtime5 import (",
        "from _ci_aggregate_diag_specs_ci import (",
        "from _ci_aggregate_diag_specs_seamgrim import (",
        "PROFILE_MATRIX_DEFAULT_SNAPSHOT",
        "CI_SANITY_DEFAULT_SNAPSHOT",
        "SEAMGRIM_FOCUS_STEP_SPECS",
        "CONTROL_EXPOSURE_POLICY_DEFAULT_SNAPSHOT",
        "REWRITE_OVERLAY_REPORT_DEFAULT_SNAPSHOT",
    ],
    "tests/_ci_aggregate_diag_specs_common.py": [
        "def build_identity_field_specs(",
        "def build_default_snapshot_from_typed_specs(",
        "CONTROL_EXPOSURE_VIOLATION_RE",
        "CONTROL_EXPOSURE_MORE_RE",
    ],
    "tests/_ci_aggregate_diag_specs_profile_runtime5.py": [
        "PROFILE_MATRIX_SNAPSHOT_FIELD_SPECS",
        "PROFILE_MATRIX_DEFAULT_SNAPSHOT",
        "PROFILE_MATRIX_SUMMARY_LINE_SPECS",
        "RUNTIME5_CHECKLIST_SNAPSHOT_FIELD_SPECS",
        "RUNTIME5_CHECKLIST_ROW_SPECS",
        *PROFILE_MATRIX_SUMMARY_TOKENS,
    ],
    "tests/_ci_aggregate_diag_specs_ci.py": [
        "from _ci_age3_completion_gate_contract import (",
        "AGE3_COMPLETION_GATE_CRITERIA_SUMMARY_KEYS,",
        "age3_completion_gate_criteria_summary_key,",
        "age3_completion_gate_criteria_sync_summary_key,",
        "def _age3_criteria_snapshot_key(name: str) -> str:",
        "AGE3_COMPLETION_GATE_CRITERIA_SNAPSHOT_KEYS",
        "CI_SANITY_DEFAULT_SNAPSHOT",
        "CI_SANITY_SNAPSHOT_FIELD_SPECS",
        "CI_SANITY_STEP_OK_SPECS",
        "CI_SANITY_SUMMARY_LINE_SPECS",
        "CI_SYNC_READINESS_DEFAULT_SNAPSHOT",
        "CI_SYNC_READINESS_SNAPSHOT_FIELD_SPECS",
        "CI_SYNC_READINESS_SUMMARY_LINE_SPECS",
        "FIXED64_THREEWAY_DEFAULT_SNAPSHOT",
        "FIXED64_THREEWAY_SNAPSHOT_FIELD_SPECS",
        "FIXED64_THREEWAY_SUMMARY_LINE_SPECS",
        *CI_SANITY_SUMMARY_TOKENS,
        *CI_SYNC_SUMMARY_TOKENS,
        *FIXED64_SUMMARY_TOKENS,
    ],
    "tests/_ci_aggregate_diag_specs_seamgrim.py": [
        "SEAMGRIM_STEP_DEFAULT_SNAPSHOT",
        "SEAMGRIM_STEP_SNAPSHOT_FIELD_SPECS",
        "SEAMGRIM_STEP_SUMMARY_LINE_SPECS",
        "SEAMGRIM_FOCUS_STEP_SPECS",
        "CONTROL_EXPOSURE_POLICY_DEFAULT_SNAPSHOT",
        "CONTROL_EXPOSURE_POLICY_SNAPSHOT_FIELD_SPECS",
        "CONTROL_EXPOSURE_POLICY_SUMMARY_LINE_SPECS",
        "REWRITE_OVERLAY_REPORT_DEFAULT_SNAPSHOT",
        "REWRITE_OVERLAY_REPORT_SNAPSHOT_FIELD_SPECS",
        "REWRITE_OVERLAY_REPORT_SUMMARY_LINE_SPECS",
        *SEAMGRIM_FOCUS_STEP_TOKEN_TUPLES,
    ],
    "tests/run_ci_gate_summary_report_check.py": [
        "from _ci_age3_completion_gate_contract import (",
        "AGE3_COMPLETION_GATE_CRITERIA_SUMMARY_KEYS,",
        "AGE3_COMPLETION_GATE_CRITERIA_SYNC_FIELD_PAIRS,",
        "for key in AGE3_COMPLETION_GATE_CRITERIA_SUMMARY_KEYS",
        "for _sanity_key, sync_key in AGE3_COMPLETION_GATE_CRITERIA_SYNC_FIELD_PAIRS",
        "PROFILE_MATRIX_SELFTEST_SCHEMA",
        "load_profile_matrix_selftest_snapshot(",
        "ci_profile_matrix_gate_selftest_report",
        *PROFILE_MATRIX_SUMMARY_TOKENS,
        *CI_SANITY_SUMMARY_TOKENS,
        "ci_profile_matrix_gate_selftest_ok",
        "ci_sanity_gate_profile",
        "ci_sync_readiness_sanity_profile",
        "seamgrim_wasm_cli_diag_parity_report",
        "seamgrim_wasm_cli_diag_parity_ok",
        "PASS summary requires seamgrim_wasm_cli_diag_parity_ok=1",
        "PASS summary requires ci_sanity_seamgrim_interface_boundary_ok=1",
        "PASS summary requires ci_sanity_overlay_session_wired_consistency_ok=1",
        "PASS summary requires ci_sanity_overlay_session_diag_parity_ok=1",
        "PASS summary requires ci_sanity_overlay_compare_diag_parity_ok=1",
        "PASS summary requires ci_sanity_pack_golden_lang_consistency_ok=1",
        "PASS summary requires ci_sanity_pack_golden_graph_export_ok=1",
        "PASS summary requires ci_sanity_contract_tier_unsupported_ok=1",
        "PASS summary requires ci_sanity_contract_tier_age3_min_enforcement_ok=1",
        "PASS summary requires ci_sanity_map_access_contract_ok=1",
        "PASS summary requires ci_sanity_stdlib_catalog_ok=1",
        "PASS summary requires ci_sanity_stdlib_catalog_selftest_ok=1",
        "PASS summary requires ci_sanity_tensor_v0_pack_ok=1",
        "PASS summary requires ci_sanity_tensor_v0_cli_ok=1",
        "PASS summary requires ci_sanity_fixed64_darwin_real_report_contract_ok=1",
        "PASS summary requires ci_sanity_fixed64_darwin_real_report_live_ok=1",
        "PASS summary requires ci_sanity_fixed64_darwin_real_report_readiness_selftest_ok=1",
        "PASS summary requires ci_sanity_registry_strict_audit_ok=1",
        "PASS summary requires ci_sanity_registry_defaults_ok=1",
        "PASS summary requires ci_profile_matrix_gate_selftest_status=pass",
        "PASS summary requires ci_profile_matrix_gate_selftest_ok=1",
        "RUNTIME5_REQUIRED_KEYS",
        "VALID_RUNTIME5_ITEM_STATUS",
        "seamgrim_5min_checklist",
        "seamgrim_runtime_5min_rewrite_motion_projectile",
        "seamgrim_runtime_5min_moyang_view_boundary",
        "PASS summary requires seamgrim_5min_checklist_ok=1",
        "PASS summary requires seamgrim_runtime_5min_rewrite_motion_projectile=1",
        "PASS summary requires seamgrim_runtime_5min_moyang_view_boundary=1",
    ],
    "tests/run_ci_sanity_gate.py": [
        *COMMON_SANITY_STEP_GATE_TOKENS,
        *COMMON_SANITY_STEP_CHECK_PATH_TOKENS,
    ],
    "tests/run_ci_sync_readiness_check.py": [
        "SANITY_REQUIRED_PASS_STEPS",
        *COMMON_SANITY_STEP_GATE_TOKENS,
        "ci_sanity_pack_golden_graph_export_ok",
        "ci_sync_readiness_ci_sanity_pack_golden_graph_export_ok",
    ],
    "tests/run_ci_emit_artifacts_check.py": [
        "SANITY_REQUIRED_PASS_STEPS",
        *COMMON_SANITY_STEP_GATE_TOKENS,
        "ci_sanity_contract_tier_unsupported_ok",
        "ci_sanity_contract_tier_age3_min_enforcement_ok",
        "ci_sanity_pack_golden_lang_consistency_ok",
        "ci_sanity_pack_golden_graph_export_ok",
        "ci_sanity_map_access_contract_ok",
        "ci_sanity_stdlib_catalog_ok",
        "ci_sanity_stdlib_catalog_selftest_ok",
        "ci_sanity_tensor_v0_pack_ok",
        "ci_sanity_tensor_v0_cli_ok",
        "ci_sanity_fixed64_darwin_real_report_contract_ok",
        "ci_sanity_fixed64_darwin_real_report_live_ok",
        "ci_sanity_fixed64_darwin_real_report_readiness_selftest_ok",
        "ci_profile_matrix_gate_selftest_ok",
        "ci_profile_matrix_gate_selftest",
        "RUNTIME5_SUMMARY_REQUIRED_KEYS",
        "VALID_RUNTIME5_ITEM_STATUS",
        "load_runtime5_checklist_snapshot(",
        "seamgrim_5min_checklist",
        "seamgrim_runtime_5min_rewrite_motion_projectile",
        "seamgrim_runtime_5min_moyang_view_boundary",
    ],
}


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    missing: list[str] = []
    fail_and_exit_contract_issues: list[str] = []
    for rel_path, tokens in REQUIRED_TOKEN_MAP.items():
        target = root / rel_path
        if not target.exists():
            print(f"missing target: {target}")
            return 1
        text = target.read_text(encoding="utf-8")
        for token in tokens:
            if token not in text:
                missing.append(f"{rel_path}::{token}")
        if rel_path == "tests/run_ci_aggregate_gate.py":
            fail_and_exit_contract_issues.extend(validate_fail_and_exit_block_contract(text))
    if missing:
        print("aggregate gate sanity diagnostics check failed:")
        for token in missing[:12]:
            print(f" - missing token: {token}")
        return 1
    if fail_and_exit_contract_issues:
        print("aggregate gate sanity diagnostics check failed (fail_and_exit contract):")
        for issue in fail_and_exit_contract_issues[:12]:
            print(f" - {issue}")
        return 1

    print("ci aggregate gate sanity diagnostics check ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
