#!/usr/bin/env python
from __future__ import annotations

from pathlib import Path

from _ci_fail_and_exit_contract import validate_fail_and_exit_block_contract
from _ci_latest_smoke_contract import (
    LATEST_SMOKE_SKIP_REASON_CI_GATE_RESULT_STATUS_NOT_PASS,
    LATEST_SMOKE_SKIP_REASON_EXPECTED,
    LATEST_SMOKE_SKIP_REASON_FAST_FAIL_PATH,
    LATEST_SMOKE_SKIP_REASON_FLAG_DISABLED,
    LATEST_SMOKE_SKIP_REASON_PENDING_FAILURE_SUMMARY_REGENERATION,
)


CI_CHECK_ERROR_CODE_TOKENS = [
    "GATE_REPORT_INDEX_CODES",
    '"SUMMARY_MISSING": "E_GATE_INDEX_SUMMARY_MISSING"',
    '"SUMMARY_EMPTY": "E_GATE_INDEX_SUMMARY_EMPTY"',
    '"SUMMARY_STATUS_MISMATCH": "E_GATE_INDEX_SUMMARY_STATUS_MISMATCH"',
    '"SUMMARY_KEY_MISSING": "E_GATE_INDEX_SUMMARY_KEY_MISSING"',
    '"SUMMARY_VALUE_INVALID": "E_GATE_INDEX_SUMMARY_VALUE_INVALID"',
    '"INDEX_MISSING": "E_GATE_INDEX_MISSING"',
    '"INDEX_JSON_INVALID": "E_GATE_INDEX_JSON_INVALID"',
    '"INDEX_SCHEMA": "E_GATE_INDEX_SCHEMA"',
    '"GENERATED_AT_MISSING": "E_GATE_INDEX_GENERATED_AT_MISSING"',
    '"GENERATED_AT_INVALID": "E_GATE_INDEX_GENERATED_AT_INVALID"',
    '"REPORT_DIR_MISSING": "E_GATE_INDEX_REPORT_DIR_MISSING"',
    '"REPORT_DIR_NOT_FOUND": "E_GATE_INDEX_REPORT_DIR_NOT_FOUND"',
    '"REPORT_PREFIX_SOURCE_INVALID": "E_GATE_INDEX_REPORT_PREFIX_SOURCE_INVALID"',
    '"REPORT_PREFIX_SOURCE_MISMATCH": "E_GATE_INDEX_REPORT_PREFIX_SOURCE_MISMATCH"',
    '"STEP_LOG_DIR_TYPE": "E_GATE_INDEX_STEP_LOG_DIR_TYPE"',
    '"STEP_LOG_DIR_NOT_FOUND": "E_GATE_INDEX_STEP_LOG_DIR_NOT_FOUND"',
    '"STEP_LOG_FAILED_ONLY_TYPE": "E_GATE_INDEX_STEP_LOG_FAILED_ONLY_TYPE"',
    '"STEP_LOG_CONFIG_MISMATCH": "E_GATE_INDEX_STEP_LOG_CONFIG_MISMATCH"',
    '"INDEX_REPORTS_MISSING": "E_GATE_INDEX_REPORTS_MISSING"',
    '"PROFILE_INVALID": "E_GATE_INDEX_PROFILE_INVALID"',
    '"PROFILE_MISMATCH": "E_GATE_INDEX_PROFILE_MISMATCH"',
    '"REPORT_KEY_MISSING": "E_GATE_INDEX_REPORT_KEY_MISSING"',
    '"REPORT_PATH_MISSING": "E_GATE_INDEX_REPORT_PATH_MISSING"',
    '"ARTIFACT_JSON_INVALID": "E_GATE_INDEX_ARTIFACT_JSON_INVALID"',
    '"ARTIFACT_SCHEMA_MISMATCH": "E_GATE_INDEX_ARTIFACT_SCHEMA_MISMATCH"',
    '"FINAL_PARSE_PARSED_MISSING": "E_GATE_INDEX_FINAL_PARSE_PARSED_MISSING"',
    '"FINAL_PARSE_STATUS_LINE_PATH_MISSING": "E_GATE_INDEX_FINAL_PARSE_STATUS_LINE_PATH_MISSING"',
    '"FINAL_PARSE_STATUS_LINE_PATH_NOT_FOUND": "E_GATE_INDEX_FINAL_PARSE_STATUS_LINE_PATH_NOT_FOUND"',
    '"FINAL_PARSE_STATUS_MISMATCH": "E_GATE_INDEX_FINAL_PARSE_STATUS_MISMATCH"',
    '"FINAL_PARSE_OVERALL_OK_INVALID": "E_GATE_INDEX_FINAL_PARSE_OVERALL_OK_INVALID"',
    '"FINAL_PARSE_OVERALL_OK_MISMATCH": "E_GATE_INDEX_FINAL_PARSE_OVERALL_OK_MISMATCH"',
    '"FINAL_PARSE_AGGREGATE_STATUS_INVALID": "E_GATE_INDEX_FINAL_PARSE_AGGREGATE_STATUS_INVALID"',
    '"FINAL_PARSE_FAILED_STEPS_TYPE": "E_GATE_INDEX_FINAL_PARSE_FAILED_STEPS_TYPE"',
    '"FINAL_PARSE_FAILED_STEPS_MISMATCH": "E_GATE_INDEX_FINAL_PARSE_FAILED_STEPS_MISMATCH"',
    '"SANITY_PROFILE_INVALID": "E_GATE_INDEX_SANITY_PROFILE_INVALID"',
    '"SANITY_PROFILE_MISMATCH": "E_GATE_INDEX_SANITY_PROFILE_MISMATCH"',
    '"SYNC_PROFILE_INVALID": "E_GATE_INDEX_SYNC_PROFILE_INVALID"',
    '"SYNC_PROFILE_MISMATCH": "E_GATE_INDEX_SYNC_PROFILE_MISMATCH"',
    '"INDEX_OVERALL_OK_TYPE": "E_GATE_INDEX_OVERALL_OK_TYPE"',
    '"INDEX_OVERALL_OK_STEPS_MISMATCH": "E_GATE_INDEX_OVERALL_OK_STEPS_MISMATCH"',
    '"RESULT_OVERALL_OK_TYPE": "E_GATE_INDEX_RESULT_OVERALL_OK_TYPE"',
    '"RESULT_OVERALL_OK_MISMATCH": "E_GATE_INDEX_RESULT_OVERALL_OK_MISMATCH"',
    '"RESULT_OK_TYPE": "E_GATE_INDEX_RESULT_OK_TYPE"',
    '"RESULT_OK_MISMATCH": "E_GATE_INDEX_RESULT_OK_MISMATCH"',
    '"RESULT_FAILED_STEPS_TYPE": "E_GATE_INDEX_RESULT_FAILED_STEPS_TYPE"',
    '"RESULT_FAILED_STEPS_MISMATCH": "E_GATE_INDEX_RESULT_FAILED_STEPS_MISMATCH"',
    '"RESULT_STATUS_MISMATCH": "E_GATE_INDEX_RESULT_STATUS_MISMATCH"',
    '"RESULT_AGGREGATE_STATUS_INVALID": "E_GATE_INDEX_RESULT_AGGREGATE_STATUS_INVALID"',
    '"RESULT_AGGREGATE_STATUS_MISMATCH": "E_GATE_INDEX_RESULT_AGGREGATE_STATUS_MISMATCH"',
    '"RESULT_SUMMARY_LINE_PATH_MISMATCH": "E_GATE_INDEX_RESULT_SUMMARY_LINE_PATH_MISMATCH"',
    '"RESULT_SUMMARY_LINE_MISMATCH": "E_GATE_INDEX_RESULT_SUMMARY_LINE_MISMATCH"',
    '"RESULT_GATE_INDEX_PATH_MISMATCH": "E_GATE_INDEX_RESULT_GATE_INDEX_PATH_MISMATCH"',
    '"RESULT_FINAL_STATUS_PARSE_PATH_MISMATCH": "E_GATE_INDEX_RESULT_FINAL_STATUS_PARSE_PATH_MISMATCH"',
    '"BADGE_RESULT_PATH_MISMATCH": "E_GATE_INDEX_BADGE_RESULT_PATH_MISMATCH"',
    '"BADGE_OK_TYPE": "E_GATE_INDEX_BADGE_OK_TYPE"',
    '"BADGE_OK_MISMATCH": "E_GATE_INDEX_BADGE_OK_MISMATCH"',
    '"BADGE_STATUS_MISMATCH": "E_GATE_INDEX_BADGE_STATUS_MISMATCH"',
    '"TRIAGE_STATUS_MISMATCH": "E_GATE_INDEX_TRIAGE_STATUS_MISMATCH"',
    '"TRIAGE_REASON_MISMATCH": "E_GATE_INDEX_TRIAGE_REASON_MISMATCH"',
    '"TRIAGE_ARTIFACTS_MISSING": "E_GATE_INDEX_TRIAGE_ARTIFACTS_MISSING"',
    '"TRIAGE_ARTIFACT_PATH_MISMATCH": "E_GATE_INDEX_TRIAGE_ARTIFACT_PATH_MISMATCH"',
    '"TRIAGE_ARTIFACT_PATH_NORM_MISMATCH": "E_GATE_INDEX_TRIAGE_ARTIFACT_PATH_NORM_MISMATCH"',
    '"TRIAGE_ARTIFACT_EXISTS_MISMATCH": "E_GATE_INDEX_TRIAGE_ARTIFACT_EXISTS_MISMATCH"',
    '"TRIAGE_SUMMARY_HINT_NORM_MISMATCH": "E_GATE_INDEX_TRIAGE_SUMMARY_HINT_NORM_MISMATCH"',
    '"STEPS_MISSING": "E_GATE_INDEX_STEPS_MISSING"',
    '"STEPS_TYPE": "E_GATE_INDEX_STEPS_TYPE"',
    '"STEP_ROW_TYPE": "E_GATE_INDEX_STEP_ROW_TYPE"',
    '"STEP_NAME": "E_GATE_INDEX_STEP_NAME"',
    '"STEP_DUP": "E_GATE_INDEX_STEP_DUP"',
    '"STEP_OK_TYPE": "E_GATE_INDEX_STEP_OK_TYPE"',
    '"STEP_OK_RC_MISMATCH": "E_GATE_INDEX_STEP_OK_RC_MISMATCH"',
    '"STEP_RC_TYPE": "E_GATE_INDEX_STEP_RC_TYPE"',
    '"STEP_CMD_TYPE": "E_GATE_INDEX_STEP_CMD_TYPE"',
    '"STEP_CMD_EMPTY": "E_GATE_INDEX_STEP_CMD_EMPTY"',
    '"STEP_CMD_ITEM_TYPE": "E_GATE_INDEX_STEP_CMD_ITEM_TYPE"',
    '"REQUIRED_STEP_MISSING": "E_GATE_INDEX_REQUIRED_STEP_MISSING"',
]

REPORT_INDEX_CHECK_TOKENS = [
        "from ci_check_error_codes import GATE_REPORT_INDEX_CODES as CODES",
        "INDEX_SCHEMA = \"ddn.ci.aggregate_gate.index.v1\"",
        "SEAMGRIM_FOCUS_SUMMARY_REQUIRED_KEYS",
        "VALID_SEAMGRIM_FOCUS_SUMMARY_STATUS",
        "def parse_summary(path: Path) -> tuple[str | None, dict[str, str], list[str]]:",
        "\"seamgrim_group_id_summary_status\"",
        "VALID_SANITY_PROFILES",
        "PROFILE_REQUIRED_STEPS_COMMON",
        "expected_profile_matrix_aggregate_summary_contract",
        "validate_profile_matrix_selftest",
        "\"ci_profile_matrix_gate_selftest\"",
        "\"ci_fail_and_exit_contract_selftest\"",
        "\"ci_emit_artifacts_required_post_summary_check\"",
        "\"ci_gate_report_index_latest_smoke_check\"",
        "PROFILE_REQUIRED_STEPS_SEAMGRIM",
        "from _ci_seamgrim_step_contract import SEAMGRIM_PROFILE_REQUIRED_STEP_CONTRACT_STEPS",
        "SEAMGRIM_PROFILE_REQUIRED_STEP_CONTRACT_STEPS",
        "resolve_profile_required_steps",
        "--sanity-profile",
        "--enforce-profile-step-contract",
        "--required-step",
        "REQUIRED_REPORT_PATH_KEYS",
        "\"final_status_parse_json\"",
        "\"seamgrim_wasm_cli_diag_parity\"",
        "\"fixed64_threeway_inputs\"",
        "ARTIFACT_SCHEMA_MAP",
        "\"ddn.ci.gate_result.v1\"",
        "\"ddn.ci.gate_badge.v1\"",
        "\"ddn.ci.fail_triage.v1\"",
        "\"ddn.ci.gate_final_status_line_parse.v1\"",
        "\"ddn.ci.status_line.parse.v1\"",
        "\"ddn.ci.profile_matrix_gate_selftest.v1\"",
        "\"ddn.ci.sanity_gate.v1\"",
        "\"ddn.ci.sync_readiness.v1\"",
        "\"ddn.seamgrim.wasm_cli_diag_parity.v1\"",
        "\"ddn.fixed64.threeway_inputs.v1\"",
        "index.steps is missing",
        "index.steps must be list",
        "index.steps[",
        "duplicate name",
        ".ok must be bool",
        "ok/returncode mismatch",
        ".returncode must be int",
        ".cmd must be list",
        ".cmd must not be empty",
        ".cmd[*] must be non-empty string",
        "invalid ci_sanity_profile",
        "ci_sanity_profile mismatch",
        "index.generated_at_utc is missing",
        "index.generated_at_utc invalid isoformat",
        "index.report_dir is missing",
        "index.report_dir not found",
        "index.report_prefix_source invalid",
        "index.report_prefix_source missing while report_prefix is set",
        "index.report_prefix_source must be empty when report_prefix is empty",
        "index.step_log_dir must be string",
        "index.step_log_dir not found",
        "index.step_log_failed_only must be bool",
        "index.step_log_failed_only=1 requires non-empty step_log_dir",
        "missing required index step(s)",
        "missing index reports key/path",
        "missing report path for",
        "artifact schema mismatch",
        "final_status_parse parsed missing",
        "final_status_parse status_line_path missing",
        "final_status_parse status_line_path not found",
        "final_status_parse status mismatch",
        "final_status_parse overall_ok invalid",
        "final_status_parse overall_ok mismatch",
        "final_status_parse aggregate_status invalid",
        "final_status_parse failed_steps must be int string",
        "final_status_parse failed_steps mismatch",
        "invalid sanity profile in ci_sanity_gate",
        "ci_sanity_gate profile mismatch",
        "ci_sanity_gate required pass step missing",
        "ci_sanity_gate required pass step not ok",
        "ci_pack_golden_lang_consistency_selftest",
        "invalid sanity_profile in ci_sync_readiness",
        "ci_sync_readiness sanity_profile mismatch",
        "index.overall_ok must be bool",
        "index.overall_ok mismatch expected=",
        "ci_gate_result overall_ok must be bool",
        "ci_gate_result overall_ok mismatch",
        "ci_gate_result ok must be bool",
        "ci_gate_result ok mismatch",
        "ci_gate_result failed_steps must be int",
        "ci_gate_result failed_steps mismatch",
        "ci_gate_result status mismatch",
        "ci_gate_result aggregate_status invalid",
        "ci_gate_result aggregate_status mismatch",
        "ci_gate_result summary_line_path mismatch",
        "ci_gate_result summary_line mismatch",
        "ci_gate_result gate_index_path mismatch",
        "ci_gate_result final_status_parse_path mismatch",
        "ci_gate_badge status mismatch",
        "ci_gate_badge ok must be bool",
        "ci_gate_badge ok mismatch",
        "ci_gate_badge result_path mismatch",
        "ci_fail_triage status mismatch",
        "ci_fail_triage reason mismatch",
        "ci_fail_triage summary_report_path_hint_norm mismatch",
        "ci_fail_triage artifacts missing",
        "ci_fail_triage artifacts path mismatch",
        "ci_fail_triage artifacts path_norm mismatch",
        "ci_fail_triage artifacts exists mismatch",
        "missing summary file:",
        "summary file is empty",
        "summary status missing or invalid",
        "summary status mismatch expected=",
        "summary missing key:",
        "summary invalid ",
        "summary requires seamgrim_group_id_summary_status=ok in pass report",
        "profile_matrix selected_real_profiles must be list",
        "profile_matrix skipped_real_profiles must be list",
        "profile_matrix real_profiles must be object",
        "profile_matrix aggregate_summary_sanity_ok must be bool",
        "profile_matrix aggregate_summary_sanity_checked_profiles must be list",
        "profile_matrix aggregate_summary_sanity_failed_profiles must be list",
        "profile_matrix aggregate_summary_sanity_skipped_profiles must be list",
        "profile_matrix aggregate_summary_sanity_by_profile must be object",
        "profile_matrix real_profiles row invalid",
        "profile_matrix aggregate_summary row invalid",
        "profile_matrix aggregate_summary expected_present invalid",
        "profile_matrix aggregate_summary ok invalid",
        "profile_matrix aggregate_summary status invalid",
        "profile_matrix aggregate_summary values invalid",
        "profile_matrix aggregate_summary value invalid",
        "profile_matrix aggregate_summary value mismatch",
        "profile_matrix aggregate_summary_sanity_ok mismatch",
]

REPORT_INDEX_SELFTEST_TOKENS = [
        "run_ci_gate_report_index_check.py",
        "summary group_id key missing case must fail",
        "summary group_id key missing code mismatch",
        "profile_matrix aggregate summary bad case must fail",
        "profile_matrix aggregate summary bad code mismatch",
        "generated_at missing case must fail",
        "generated_at invalid case must fail",
        "report_dir missing case must fail",
        "report_dir not found case must fail",
        "report_prefix_source invalid case must fail",
        "report_prefix_source mismatch case must fail",
        "report_prefix_source env-empty case must fail",
        "report_prefix_source env-ok case should pass",
        "step_log_dir type case must fail",
        "step_log_failed_only type case must fail",
        "step_log config mismatch case must fail",
        "step_log_dir not found case must fail",
        "missing key case must fail",
        "missing fixed64 key case must fail",
        "missing path case must fail",
        "bad schema case must fail",
        "final parse parsed missing case must fail",
        "final parse status_line_path missing case must fail",
        "final parse status_line_path not found case must fail",
        "final parse status mismatch case must fail",
        "final parse overall_ok invalid case must fail",
        "final parse overall_ok mismatch case must fail",
        "final parse aggregate_status invalid case must fail",
        "final parse failed_steps type case must fail",
        "final parse failed_steps mismatch case must fail",
        "missing required step case must fail",
        "bad step shape case must fail",
        "bad profile case must fail",
        "profile mismatch case must fail",
        "cmd empty case must fail",
        "cmd item type case must fail",
        "ok/rc mismatch case must fail",
        "sanity profile mismatch case must fail",
        "sanity required lang consistency step missing case must fail",
        "sanity required lang consistency step fail case must fail",
        "core_lang profile missing lang consistency sanity step case must fail",
        "sync profile mismatch case must fail",
        "index overall_ok type case must fail",
        "index overall_ok steps mismatch case must fail",
        "result overall_ok type case must fail",
        "result overall_ok mismatch case must fail",
        "result ok type case must fail",
        "result ok mismatch case must fail",
        "result failed_steps type case must fail",
        "result failed_steps mismatch case must fail",
        "result status mismatch case must fail",
        "result aggregate_status invalid case must fail",
        "result aggregate_status mismatch case must fail",
        "result summary_line_path mismatch case must fail",
        "result summary_line mismatch case must fail",
        "result gate_index_path mismatch case must fail",
        "result final_status_parse_path mismatch case must fail",
        "badge status mismatch case must fail",
        "badge ok type case must fail",
        "badge ok mismatch case must fail",
        "badge result_path mismatch case must fail",
        "triage status mismatch case must fail",
        "triage reason mismatch case must fail",
        "triage summary_hint_norm mismatch case must fail",
        "triage artifacts missing case must fail",
        "triage artifact path mismatch case must fail",
        "triage artifact path_norm mismatch case must fail",
        "triage artifact exists mismatch case must fail",
        "PROFILE_INVALID",
        "PROFILE_MISMATCH",
        "GENERATED_AT_MISSING",
        "GENERATED_AT_INVALID",
        "REPORT_DIR_MISSING",
        "REPORT_DIR_NOT_FOUND",
        "REPORT_PREFIX_SOURCE_INVALID",
        "REPORT_PREFIX_SOURCE_MISMATCH",
        "STEP_LOG_DIR_TYPE",
        "STEP_LOG_DIR_NOT_FOUND",
        "STEP_LOG_FAILED_ONLY_TYPE",
        "STEP_LOG_CONFIG_MISMATCH",
        "SANITY_PROFILE_MISMATCH",
        "SYNC_PROFILE_MISMATCH",
        "INDEX_OVERALL_OK_TYPE",
        "INDEX_OVERALL_OK_STEPS_MISMATCH",
        "RESULT_OVERALL_OK_TYPE",
        "RESULT_OVERALL_OK_MISMATCH",
        "RESULT_OK_TYPE",
        "RESULT_OK_MISMATCH",
        "RESULT_FAILED_STEPS_TYPE",
        "RESULT_FAILED_STEPS_MISMATCH",
        "RESULT_STATUS_MISMATCH",
        "RESULT_SUMMARY_LINE_PATH_MISMATCH",
        "RESULT_SUMMARY_LINE_MISMATCH",
        "RESULT_GATE_INDEX_PATH_MISMATCH",
        "RESULT_FINAL_STATUS_PARSE_PATH_MISMATCH",
        "BADGE_OK_TYPE",
        "BADGE_OK_MISMATCH",
        "BADGE_STATUS_MISMATCH",
        "BADGE_RESULT_PATH_MISMATCH",
        "TRIAGE_STATUS_MISMATCH",
        "TRIAGE_REASON_MISMATCH",
        "TRIAGE_ARTIFACTS_MISSING",
        "TRIAGE_ARTIFACT_PATH_MISMATCH",
        "TRIAGE_ARTIFACT_PATH_NORM_MISMATCH",
        "TRIAGE_ARTIFACT_EXISTS_MISMATCH",
        "TRIAGE_SUMMARY_HINT_NORM_MISMATCH",
        "REPORT_KEY_MISSING",
        "REPORT_PATH_MISSING",
        "ARTIFACT_JSON_INVALID",
        "ARTIFACT_SCHEMA_MISMATCH",
        "FINAL_PARSE_PARSED_MISSING",
        "FINAL_PARSE_STATUS_LINE_PATH_MISSING",
        "FINAL_PARSE_STATUS_LINE_PATH_NOT_FOUND",
        "FINAL_PARSE_STATUS_MISMATCH",
        "FINAL_PARSE_OVERALL_OK_INVALID",
        "FINAL_PARSE_OVERALL_OK_MISMATCH",
        "FINAL_PARSE_AGGREGATE_STATUS_INVALID",
        "FINAL_PARSE_FAILED_STEPS_TYPE",
        "FINAL_PARSE_FAILED_STEPS_MISMATCH",
        "RESULT_AGGREGATE_STATUS_INVALID",
        "RESULT_AGGREGATE_STATUS_MISMATCH",
        "REQUIRED_STEP_MISSING",
        "STEP_ROW_TYPE",
        "STEP_OK_RC_MISMATCH",
        "STEP_CMD_EMPTY",
        "STEP_CMD_ITEM_TYPE",
        "REQUIRED_STEPS",
        "sanity_profile",
        "enforce_profile_step_contract",
        "core_lang profile should allow missing seamgrim steps",
        "seamgrim profile should allow missing lang consistency sanity step",
        "seamgrim profile missing parity step case must fail",
        "seamgrim profile missing v2 task batch step case must fail",
        "seamgrim profile missing v2 task batch step code mismatch",
        "seamgrim profile failed v2 task batch step case must fail",
        "seamgrim profile failed v2 task batch step code mismatch",
        "seamgrim_v2_task_batch_check",
        "SEAMGRIM_BLOCKER_GATE_REPORT_INDEX_MISSING_STEP_CASES",
        "for missing_step_name, fail_message, code_message in SEAMGRIM_BLOCKER_GATE_REPORT_INDEX_MISSING_STEP_CASES:",
        "SEAMGRIM_BLOCKER_GATE_REPORT_INDEX_FAILED_STEP_CASES",
        "for failed_step_name, fail_message, code_message in SEAMGRIM_BLOCKER_GATE_REPORT_INDEX_FAILED_STEP_CASES:",
        "SEAMGRIM_FEATURED_GATE_REPORT_INDEX_MISSING_STEP_CASES",
        "for missing_step_name, fail_message, code_message in SEAMGRIM_FEATURED_GATE_REPORT_INDEX_MISSING_STEP_CASES:",
        "SEAMGRIM_FEATURED_GATE_REPORT_INDEX_FAILED_STEP_CASES",
        "for failed_step_name, fail_message, code_message in SEAMGRIM_FEATURED_GATE_REPORT_INDEX_FAILED_STEP_CASES:",
        "SEAMGRIM_PLATFORM_GATE_REPORT_INDEX_MISSING_STEP_CASES",
        "for missing_step_name, fail_message, code_message in SEAMGRIM_PLATFORM_GATE_REPORT_INDEX_MISSING_STEP_CASES:",
        "SEAMGRIM_PLATFORM_GATE_REPORT_INDEX_FAILED_STEP_CASES",
        "for failed_step_name, fail_message, code_message in SEAMGRIM_PLATFORM_GATE_REPORT_INDEX_FAILED_STEP_CASES:",
        "seamgrim_ci_gate_wasm_web_smoke_step_check_selftest",
        "ci_profile_matrix_gate_selftest",
        "ci_emit_artifacts_required_post_summary_check",
        "ci_gate_report_index_latest_smoke_check",
        "tests/run_ci_gate_report_index_latest_smoke_check.py",
        "--required-step",
]

AGGREGATE_GATE_TOKENS = [
        "check_ci_gate_report_index",
        "check_ci_gate_report_index_selftest",
        "check_ci_gate_report_index_diagnostics",
        "check_ci_fail_and_exit_contract_selftest",
        "check_ci_fail_and_exit_contract_selftest_skipped",
        "check_ci_gate_report_index_latest_smoke",
        "check_seamgrim_ci_gate_wasm_web_smoke_step_selftest",
        "seamgrim_ci_gate_wasm_web_smoke_step_check_selftest",
        "tests/run_seamgrim_ci_gate_wasm_web_smoke_step_check_selftest.py",
        "check_ci_profile_matrix_gate_selftest",
        "ci_profile_matrix_gate_selftest",
        "tests/run_ci_profile_matrix_gate_selftest.py",
        "ci_emit_artifacts_required_post_summary_check",
        "report_index_required_steps_common",
        "report_index_required_steps_seamgrim",
        "resolve_report_index_required_steps",
        "report_index_required_steps",
        "require_step_contract",
        "--sanity-profile",
        "--enforce-profile-step-contract",
        "--required-step",
        "check_ci_gate_report_index(require_step_contract=True)",
        "def find_step_record(name: str) -> dict[str, object] | None:",
        "def run_step_if_missing(name: str, runner) -> int:",
        'run_step_if_missing("ci_fail_and_exit_contract_selftest", check_ci_fail_and_exit_contract_selftest)',
        'run_step_if_missing("ci_gate_report_index_selftest", check_ci_gate_report_index_selftest)',
        'run_step_if_missing("ci_gate_report_index_diagnostics_check", check_ci_gate_report_index_diagnostics)',
        'run_step_if_missing("ci_emit_artifacts_baseline_check", check_ci_emit_artifacts_baseline)',
        "ci_fail_and_exit_contract_selftest",
        "ci_gate_report_index_check",
        "ci_gate_report_index_selftest",
        "ci_gate_report_index_diagnostics_check",
        "ci_gate_report_index_latest_smoke_check",
        "tests/run_ci_gate_report_index_check.py",
        "tests/run_ci_gate_report_index_check_selftest.py",
        "tests/run_ci_gate_report_index_diagnostics_check.py",
        "tests/run_ci_fail_and_exit_contract_selftest.py",
        "tests/run_ci_gate_report_index_latest_smoke_check.py",
        "--skip-fail-and-exit-contract-selftest",
]

LATEST_SMOKE_SKIP_REASON_EXPECTED_TOKENS = [
    "LATEST_SMOKE_SKIP_REASON_EXPECTED",
    "LATEST_SMOKE_SKIP_REASON_FAST_FAIL_PATH",
    "LATEST_SMOKE_SKIP_REASON_FLAG_DISABLED",
    "LATEST_SMOKE_SKIP_REASON_PENDING_FAILURE_SUMMARY_REGENERATION",
    "LATEST_SMOKE_SKIP_REASON_CI_GATE_RESULT_STATUS_NOT_PASS",
]

LATEST_SMOKE_REASON_BRANCH_TOKENS = [
    "from _ci_latest_smoke_contract import (",
    "def check_ci_gate_report_index_latest_smoke_skipped(reason: str) -> int:",
    "def should_run_ci_gate_report_index_latest_smoke() -> bool:",
    "return LATEST_SMOKE_SKIP_REASON_FLAG_DISABLED",
    "return LATEST_SMOKE_SKIP_REASON_PENDING_FAILURE_SUMMARY_REGENERATION",
    "return LATEST_SMOKE_SKIP_REASON_CI_GATE_RESULT_STATUS_NOT_PASS",
    "def resolve_ci_gate_report_index_latest_smoke_skip_reason(",
    "def run_ci_gate_report_index_latest_smoke_step(",
    "check_ci_gate_report_index_latest_smoke_skipped(LATEST_SMOKE_SKIP_REASON_FAST_FAIL_PATH)",
    "ci_gate_report_index_latest_smoke_rc = run_ci_gate_report_index_latest_smoke_step(",
    "if not bool(args.run_report_index_latest_smoke):",
    "elif has_failed_steps or ci_gate_report_index_rc != 0:",
    "elif should_run_ci_gate_report_index_latest_smoke():",
    *LATEST_SMOKE_SKIP_REASON_EXPECTED_TOKENS,
]

REQUIRED_TOKEN_MAP = {
    "tests/ci_check_error_codes.py": CI_CHECK_ERROR_CODE_TOKENS,
    "tests/run_ci_gate_report_index_check.py": REPORT_INDEX_CHECK_TOKENS,
    "tests/run_ci_gate_report_index_check_selftest.py": REPORT_INDEX_SELFTEST_TOKENS,
    "tests/run_ci_aggregate_gate.py": AGGREGATE_GATE_TOKENS + LATEST_SMOKE_REASON_BRANCH_TOKENS,
}


def main() -> int:
    expected_reason_set = {
        LATEST_SMOKE_SKIP_REASON_FAST_FAIL_PATH,
        LATEST_SMOKE_SKIP_REASON_FLAG_DISABLED,
        LATEST_SMOKE_SKIP_REASON_PENDING_FAILURE_SUMMARY_REGENERATION,
        LATEST_SMOKE_SKIP_REASON_CI_GATE_RESULT_STATUS_NOT_PASS,
    }
    if set(LATEST_SMOKE_SKIP_REASON_EXPECTED) != expected_reason_set:
        print("ci gate report-index diagnostics check failed: latest-smoke reason contract mismatch")
        return 1

    root = Path(__file__).resolve().parent.parent
    missing: list[str] = []
    for rel_path, tokens in REQUIRED_TOKEN_MAP.items():
        target = root / rel_path
        if not target.exists():
            print(f"missing target: {target}")
            return 1
        text = target.read_text(encoding="utf-8")
        for token in tokens:
            if token not in text:
                missing.append(f"{rel_path}::{token}")

    if missing:
        print("ci gate report-index diagnostics check failed:")
        for token in missing[:16]:
            print(f" - missing token: {token}")
        return 1
    aggregate_gate_target = root / "tests" / "run_ci_aggregate_gate.py"
    if not aggregate_gate_target.exists():
        print(f"missing target: {aggregate_gate_target}")
        return 1
    fail_and_exit_contract_issues = validate_fail_and_exit_block_contract(
        aggregate_gate_target.read_text(encoding="utf-8")
    )
    if fail_and_exit_contract_issues:
        print("ci gate report-index diagnostics check failed (fail_and_exit contract):")
        for issue in fail_and_exit_contract_issues[:16]:
            print(f" - {issue}")
        return 1

    print("ci gate report-index diagnostics check ok")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
